# -*- coding: utf-8 -*-
"""'Books' part of product categories dictionary.

Must hold subcategories of 'Books'
category in the form of python dictionary data type.

"""
books = {('books', 'книги'): {
    ('audiobooks', 'аудиокниги'): {
        ('biography', 'биографии'): {},
        ('business, economics', 'бизнес, экономика'): {},
        ('kids', 'детское'): {},
        ('fiction, literature', 'художественная литература'): {},
        ('health, fitness', 'здоровье, фитнес'): {},
        ('history', 'история'): {},
        ('humor', 'юмор'): {},
        ('parenting, family', 'семья, воспитание'): {},
        ('philosophy', 'философия'): {},
        ('poetry', 'поэзия'): {},
        ('psychology', 'психология'): {},
        ('religion, spirituality', 'религия, духовность'): {},
        ('science, medicine', 'наука, медицина'): {},
        ('self-help', 'самопомощь'): {},
        ('travel', 'путешествия'): {},
        ('other', 'другое'): {},
    },
    ('kids', 'детское'): {
        ('ABCs, numbers', 'алфавит, числа'): {},
        ('activity, coloring books', 'раскраски, игры'): {},
        ('bedtime', 'перед сном'): {},
        ('classics', 'классика'): {},
        ('fairy tales, myths', 'сказки, мифы'): {},
        ('fiction', 'художественная литература'): {},
        ('geography', 'география'): {},
        ('history', 'история'): {},
        ('humor', 'юмор'): {},
        ('learning to read', 'учимся читать'): {},
        ('nursery rhymes', 'стишки'): {},
        ('picture books', 'иллюстрированные книги'): {},
        ('poetry', 'поэзия'): {},
        ('pop-up, movable', '3D, подвижные'): {},
        ('religion', 'религия'): {},
        ('science, nature', 'наука, природа'): {},
        ('sports', 'спорт'): {},
        ('foreign language', 'иностранный язык'): {},
        ('other', 'другое'): {},
    },
    ('poetry', 'поэзия'): {},
    ('cookbooks', 'кулинарные книги'): {},
    ('comic books', 'комиксы'): {},
    ('fiction', 'художественная литература'): {
        ('action, adventure', 'приключения'): {},
        ('classics', 'классика'): {},
        ('drama', 'драма'): {},
        ('fantasy', 'фэнтези'): {},
        ('folklore, mythology', 'фольклор, мифология'): {},
        ('historical', 'историческое'): {},
        ('horror', 'ужасы'): {},
        ('humor', 'юмор'): {},
        ('military', 'военное'): {},
        ('mystery, thriller', 'мистерия, триллер'): {},
        ('religious', 'религиозное'): {},
        ('romance', 'романтичное'): {},
        ('science fiction', 'научная фантастика'): {},
        ('foreign language', 'иностранный язык'): {},
        ('other', 'другое'): {},
    },
    ('non-fiction', 'научно-популярные'): {
        ('antiques, collectibles', 'антиквариат, коллекционное'): {}, ('architecture', 'архитектура'): {},
        ('art', 'живопись, искусство'): {},
        ('photography', 'фотография'): {},
        ('biography', 'биографии'): {},
        ('business, economics', 'бизнес, экономика'): {},
        ('craft', 'рукоделие, ремесло'): {},
        ('food, cooking', 'продукты, поваренные'): {},
        ('design', 'дизайн'): {},
        ('flora, fauna', 'флора, фауна'): {},
        ('computers, internet', 'компьютер, интернет'): {},
        ('family, relationships', 'семья, отношения'): {},
        ('games, puzzles', 'игры, пазлы'): {},
        ('health, fitness', 'здоровье, фитнес'): {},
        ('history', 'история'): {},
        ('hobbies', 'хобби'): {},
        ('home, garden', 'дом, сад'): {},
        ('humor', 'юмор'): {},
        ('law', 'право'): {},
        ('medical', 'медицина'): {},
        ('military, war', 'военное'): {},
        ('movies, tv', 'фильмы, тв'): {},
        ('music', 'музыка'): {},
        ('outdoor, nature', 'на природе'): {},
        ('performing arts', 'исполнительное искусство'): {},
        ('pets', 'домашние животные'): {},
        ('philosophy', 'философия'): {},
        ('politics', 'политика'): {},
        ('psychology', 'психология'): {},
        ('reference', 'справочники'): {},
        ('religion, spirituality', 'религия, духовность'): {},
        ('science, tech', 'наука, технология'): {},
        ('self-help', 'самопомощь'): {},
        ('social sciences', 'общественные науки'): {},
        ('sports, recreation', 'спорт, активный отдых'): {},
        ('teaching, education', 'обучение, образование'): {},
        ('transport', 'транспорт'): {},
        ('travel', 'путешествия'): {},
        ('other', 'другое'): {},
    },
    ('school textbooks', 'школьные учебники'): {
        ('biology', 'биология'): {},
        ('business, economics', 'бизнес, экономика'): {},
        ('computers, internet', 'компьютер, интернет'): {},
        ('chemistry', 'химия'): {},
        ('english, grammar', 'английский'): {},
        ('foreign language', 'иностранный язык'): {},
        ('geography', 'география'): {},
        ('history', 'история'): {},
        ('humanities', 'гуманитарные науки'): {},
        ('math', 'математика'): {},
        ('music', 'музыка'): {},
        ('performing arts', 'исполнительное искусство'): {},
        ('philosophy', 'философия'): {},
        ('physics', 'физика'): {},
        ('psychology', 'психология'): {},
        ('reference', 'справочники'): {},
        ('religion', 'религия'): {},
        ('science, tech', 'наука, технология'): {},
        ('social sciences', 'общественные науки'): {},
        ('sports', 'спорт'): {},
        ('other', 'другое'): {},
    },
    ('textbooks', 'учебники'): {
        ('accounting', 'бухгалтерия'): {},
        ('architecture, design', 'архитектура, дизайн'): {},
        ('art, photography', 'искусство, фотография'): {},
        ('biology', 'биология'): {},
        ('business, economics', 'бизнес, экономика'): {},
        ('computers, internet', 'компьютер, интернет'): {},
        ('chemistry', 'химия'): {},
        ('engineering', 'инжиниринг, технологии'): {},
        ('english, grammar', 'английский'): {},
        ('foreign language', 'иностранный язык'): {},
        ('gardening, landscaping', 'ландшафт, садоводство'): {},
        ('genetics', 'генетика'): {},
        ('geography', 'география'): {},
        ('history', 'история'): {},
        ('humanities', 'гуманитарные науки'): {},
        ('linguistics', 'лингвистика'): {},
        ('law', 'право'): {},
        ('management', 'менеджмент, управление'): {},
        ('math', 'математика'): {},
        ('medicine', 'медицина'): {},
        ('marketing', 'маркетинг'): {},
        ('music', 'музыка'): {},
        ('performing arts', 'исполнительное искусство'): {},
        ('philosophy', 'философия'): {},
        ('physics', 'физика'): {},
        ('political science', 'политические науки'): {},
        ('psychology', 'психология'): {},
        ('reference', 'справочники'): {},
        ('religion', 'религия'): {},
        ('science, tech', 'наука, технология'): {},
        ('social sciences', 'общественные науки'): {},
        ('sports', 'спорт'): {},
        ('teaching, education', 'обучение, образование'): {},
        ('other', 'другое'): {},
    },
    ('other', 'другое'): {},
}
}
