# -*- coding: utf-8 -*-
"""'business, industry' part of product categories dictionary.

Must hold subcategories of 'business, industry'
category in the form of python dictionary data type.

"""
business_industry = {('business, industry', 'бизнес, индустрия'): {
    ('businesses for sale', 'бизнес на продажу'): {
        ('internet', 'интернет'): {},
        ('manufacturing', 'производство'): {},
        ('retail', 'розничная торговля'): {},
        ('services', 'услуги'): {},
        ('tourism, hospitality', 'туризм, гостеприимство'): {
            ('accommodation', 'проживание'): {},
            ('restaurants, bars, cafes', 'рестораны, бары, кафе'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('farming, forestry', 'фермерство, лесхоз'): {
        ('beekeeping', 'пчеловодство'): {},
        ('forestry', 'лесное хозяйство'): {
            ('machinery, equipment', 'машины, оборудование'): {},
            ('supplies', 'расходные материалы'): {},
            ('other', 'другое'): {},
        },
        ('livestock, supplies', 'домашний скот, оборудование'): {
            ('feeding, watering', 'кормление'): {
                ('feeders', 'питатели'): {},
                ('troughs', 'кормушки'): {},
                ('hay', 'сено'): {},
                ('silage', 'силос'): {},
                ('other', 'другое'): {},
            },
            ('fencing', 'ограждение'): {
                ('electric', 'электро'): {},
                ('gates', 'ворота'): {},
                ('posts', 'столбы'): {},
                ('wire', 'проволка'): {},
                ('other', 'другое'): {},
            },
            ('cattle', 'крупный рогатый скот'): {
                ('beef', 'мясной'): {},
                ('dairy', 'молочный'): {},
                ('other', 'другое'): {},
            },
            ('goats', 'козы'): {},
            ('horse', 'лошади'): {},
            ('pigs', 'свиньи'): {},
            ('sheep', 'овцы'): {},
            ('animal health', 'здоровье животных'): {},
            ('other', 'другое'): {},
        },
        ('paultry', 'птица'): {
            ('bantams', 'петухи'): {},
            ('chickens', 'курицы'): {},
            ('ducks', 'утки'): {},
            ('feeding, watering', 'кормление'): {},
            ('housing', 'укрытия, помещения'): {},
            ('other birds', 'другая птица'): {},
            ('other', 'другое'): {},
        },
        ('tractor attachments', 'тракторные приспособления'): {
            ('balers', 'пресс-подборщик'): {},
            ('cultivators', 'культиваторы'): {},
            ('hoes, ploughs', 'плуги'): {},
            ('loaders', 'погрузчики'): {},
            ('mowers', 'косилки'): {},
            ('harvesting equipment', 'уборочная техника'): {},
            ('hay rakes', 'грабли для сена'): {},
            ('planters', 'плантеры'): {},
            ('parts', 'запчасти'): {},
            ('seeders, spreaders', 'сеялки, спредеры'): {},
            ('sprayers', 'опрыскиватели'): {},
            ('tillers', 'тиллеры'): {},
            ('wheels, tyres', 'колеса, покрышки'): {},
            ('other', 'другое'): {},
        },
        ('tractors, farm machinery', 'тракторы, сельхоз техника'): {
            ('combines', 'комбайны'): {},
            ('tractors', 'тракторы'): {},
            ('trailers', 'трeйлеры'): {},
            ('utility vehicles', 'многоцелевые'): {},
            ('parts', 'запчасти'): {},
            ('other', 'другое'): {},
        },
    },
    ('industrial', 'производство'): {
        ('compressors, pumps', 'компрессоры, насосы'): {
            ('compressors', 'компрессоры'): {},
            ('pumps', 'насосы'): {},
            ('other', 'другое'): {},
        },
        ('storage, containers', 'хранение, контейнеры'): {
            ('shipping containers', 'морские контейнеры'): {},
            ('shelves', 'стелажи, полки'): {},
            ('bins', 'ящики, бункеры'): {},
            ('other', 'другое'): {},
        },
        ('earthmoving machinery', 'землеройные машины'): {
            ('bulldozers', 'бульдозеры'): {},
            ('diggers, excavators', 'экскаваторы, землеройные'): {},
            ('loaders', 'погрузчики'): {},
            ('other machines', 'другие машины'): {},
            ('parts, attachments', 'запчасти, приспособления'): {},
            ('other', 'другое'): {},
        },
        ('electrical equipment', 'электро оборудование'): {
            ('fuses', 'предохранители'): {},
            ('transformers', 'трансформаторы'): {},
            ('tools', 'инструмент'): {},
            ('electronic components', 'электроника'): {
                ('batteries, power supplies', 'батареи, питание'): {},
                ('converters', 'преобразователи'): {},
                ('fans', 'вентиляторы'): {},
                ('heatsinks', 'радиаторы'): {},
                ('indicators', 'индикаторы'): {},
                ('capacitors', 'конденсаторы'): {},
                ('ICs, processors', 'микросхемы'): {},
                ('LEDs', 'светодиоды'): {},
                ('passive components', 'пассивные компоненты'): {},
                ('active components', 'активные компоненты'): {},
                ('semiconductors', 'полупроводники'): {},
                ('voltage regulators', 'стабилизаторы'): {},
                ('other', 'другое'): {},
            },
            ('gauges, meters', 'датчики, измерители'): {},
            ('lights', 'лампочки'): {},
            ('other', 'другое'): {},
        },
        ('engines, motors', 'двигатели, моторы'): {
            ('diesel', 'дизель'): {},
            ('electric', 'электро'): {},
            ('petrol', 'бензин'): {},
            ('other', 'другое'): {},
        },
        ('forklifts, pallet movers', 'погрузчики, штабелеры'): {},
        ('heaters, generators', 'обогреватели, генераторы'): {
            ('heaters', 'обогреватели'): {},
            ('generators', 'генераторы'): {
                ('diesel', 'дизель'): {},
                ('petrol', 'бензин'): {},
                ('solar', 'солнечные'): {},
                ('wind', 'ветровые'): {},
                ('other', 'другое'): {},
            },
            ('other', 'другое'): {},
        },
        ('hoists, jacks', 'подъемники, домкраты'): {},
        ('metalwork', 'металлообработка'): {
            ('drills, accessories', 'дрели, аксессуары'): {},
            ('dust collectors, extractors', 'пылезборники, экстракторы'): {},
            ('grinders', 'шлифмашины'): {},
            ('lathes, accessories', 'токарные станки'): {},
            ('metal, supplies', 'металл, расходные'): {},
            ('presses', 'прессы'): {},
            ('saws, blades', 'пилы, полотна'): {},
            ('vices', 'тиски'): {},
            ('welders', 'сварочные аппараты'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('measuring, scales', 'измерения, весы'): {},
        ('water blasters', 'водяные бластеры'): {},
        ('safety, security', 'безопасность'): {
            ('alarm systems', 'системы сигнализации'): {},
            ('emergency lights', 'аварийное освещение'): {},
            ('fire protection', 'противопожарное'): {},
            ('safety gear', 'защитное снаряжение'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('office', 'офис'): {
        ('equipment, supplies', 'оборудование, расходные'): {
            ('binding', 'переплет'): {},
            ('copying', 'копирование'): {},
            ('label making', 'маркировка'): {},
            ('laminating', 'ламинирование'): {},
            ('shredders', 'шредеры'): {},
            ('whiteboards', 'доски'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('furniture', 'мебель'): {
            ('shelves', 'полки'): {},
            ('chairs', 'кресла, стулья'): {},
            ('filing', 'работа с файлами'): {},
            ('partitions', 'перегородки'): {},
            ('desks, tables', 'столы'): {},
            ('workstations', 'рабочие комплексы'): {},
            ('cabinets', 'шкафы'): {},
            ('drawers', 'тумбы'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('stationery', 'канцтовары'): {
            ('organisers', 'органайзеры'): {},
            ('filing', 'файлы'): {},
            ('pencils', 'карандаши'): {},
            ('pens', 'ручки'): {},
            ('markers', 'маркеры'): {},
            ('paper products', 'бумага'): {},
            ('stamps', 'печати, штампы'): {},
            ('storage', 'хранение'): {},
            ('staplers, staples', 'степлеры, скобы'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('packing, shipping', 'упаковка, рассылка'): {
        ('bags', 'мешки'): {},
        ('boxes', 'коробки'): {},
        ('envelopes', 'конверты'): {},
        ('tape', 'упаковочная лента'): {},
        ('shrink wrap', 'термоусадочная пленка'): {},
        ('bubble wrap', 'пузырчатая пленка'): {},
        ('cushion wrap', 'мягкая пленка'): {},
        ('other', 'другое'): {},
    },
    ('restaurant, catering', 'рестораны, кейтеринг'): {
        ('kitchen equipment', 'кухонное оборудование'): {
            ('benches', 'столы, столешницы'): {},
            ('coffee, beverage', 'для кофе, напитков'): {},
            ('deep fryers', 'фритюрница'): {},
            ('dishwashers', 'посудомоечные машины'): {},
            ('grills', 'грили'): {},
            ('ovens', 'печи, духовки'): {},
            ('warmers', 'подогрев'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('kitchenware', 'кухонная утварь'): {
            ('plates', 'тарелки'): {},
            ('glassware', 'стекло'): {},
            ('cutlery', 'столовые приборы'): {},
            ('disposable', 'одноразовое'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('refrigeration', 'охлаждение'): {
            ('display fridges', 'дисплей холодильники'): {},
            ('freezers', 'морозильники'): {},
            ('refrigerators', 'холодильники'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('furniture', 'мебель'): {
            ('bars, stools', 'бары, стулья'): {},
            ('chairs', 'кресла, стулья'): {},
            ('tables', 'столы'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('signs', 'реклама, вывески'): {
            ('illuminated', 'световые'): {},
            ('banners', 'баннеры'): {},
            ('flags', 'флаги'): {},
            ('programmable', 'программируемые'): {},
            ('letters', 'буквы'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('retail', 'розничная торговля'): {
        ('furniture', 'мебель'): {},
        ('point of sale equipment', 'точка продажи'): {
            ('barcode scanners', 'сканеры баркодов'): {},
            ('computer systems', 'компьютерные системы'): {},
            ('credit card terminals', 'терминалы карт'): {},
            ('registers', 'кассовые аппараты'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('displays', 'дисплей товаров'): {
            ('baskets, bins', 'корзины, контейнеры'): {},
            ('book, magazine holders', 'журнальные стенды'): {},
            ('cabinets', 'шкафы'): {},
            ('clothing racks', 'развес одежды'): {},
            ('counters, benches', 'прилавки, стойки'): {},
            ('food, drink displays', 'дисплей напитков, продуктов'): {},
            ('jewellery racks, stands', 'дисплей драгоценностей'): {},
            ('shelves', 'стелажи, полки'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('labeling, tagging', 'маркировка'): {},
        ('mannequins', 'манекены'): {},
        ('refrigeration', 'охлаждение'): {
            ('display fridges', 'дисплей холодильники'): {},
            ('freezers', 'морозильники'): {},
            ('refrigerators', 'холодильники'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('signs', 'реклама, вывески'): {
            ('illuminated', 'световые'): {},
            ('banners', 'баннеры'): {},
            ('flags', 'флаги'): {},
            ('programmable', 'программируемые'): {},
            ('letters', 'буквы'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('other', 'другое'): {},
}
}
