# -*- coding: utf-8 -*-
"""'computers' part of product categories dictionary.

Must hold subcategories of 'computers'
category in the form of python dictionary data type.

"""
laptop_brands = {
    ('acer', 'acer'): {},
    ('apple', 'apple'): {},
    ('asus', 'asus'): {},
    ('compaq', 'compaq'): {},
    ('dell', 'dell'): {},
    ('hp', 'hp'): {},
    ('IBM', 'IBM'): {},
    ('lenovo', 'lenovo'): {},
    ('samsung', 'samsung'): {},
    ('sony', 'sony'): {},
    ('toshiba', 'toshiba'): {},
    ('other', 'другое'): {},
}
computers = {('computers', 'компьютеры'): {
    ('accessories', 'аксессуары'): {
        ('headsets, microphones', 'наушники, микрофоны'): {},
        ('keyboards', 'клавиатура'): {
            ('ergonomic', 'эргономичные'): {},
            ('flexible', 'гибкие'): {},
            ('gaming', 'игровые'): {},
            ('illuminated', 'подсвеченные'): {},
            ('mini', 'мини'): {},
            ('multimedia', 'мультимедийные'): {},
            ('standard', 'стандартные'): {},
            ('other', 'другое'): {},
        },
        ('mice', 'мыши'): {
            ('wired', 'проводные'): {},
            ('wireless', 'беспроводные'): {},
            ('other', 'другое'): {},
        },
        ('scanners', 'сканеры'): {},
        ('speakers', 'колонки'): {},
        ('UPS', 'UPS'): {},
        ('USB Hubs', 'USB-концентраторы'): {},
        ('webcams', 'веб-камеры'): {},
        ('wrist, mouse pads', 'коврики для мышек'): {},
        ('other', 'другое'): {},
    },
    ('all-in-ones', 'все в одном'): {
        ('acer', 'acer'): {},
        ('apple', 'apple'): {},
        ('asus', 'asus'): {},
        ('compaq', 'compaq'): {},
        ('dell', 'dell'): {},
        ('gateway', 'gateway'): {},
        ('hp', 'hp'): {},
        ('lenovo', 'lenovo'): {},
        ('msi', 'msi'): {},
        ('samsung', 'samsung'): {},
        ('sony', 'sony'): {},
        ('toshiba', 'toshiba'): {},
        ('viewsonic', 'viewsonic'): {},
        ('other', 'другое'): {},
    },
    ('blank discs', 'чистые диски'): {
        ('cases, wallets', 'футляры, альбомы'): {},
        ('CD', 'CD'): {},
        ('DVD', 'DVD'): {},
        ('BD', 'BD'): {},
        ('other', 'другое'): {},
    },
    ('cables, adaptors', 'кабели, адаптеры'): {
        ('audio', 'аудио'): {},
        ('printer', 'принтеры'): {},
        ('IDE, SCSI', 'IDE, SCSI'): {},
        ('ATA, SATA, eSATA', 'ATA, SATA, eSATA'): {},
        ('firewire', 'firewire'): {},
        ('monitor', 'мониторы'): {},
        ('networking', 'сетевые'): {},
        ('power', 'питание'): {},
        ('USB', 'USB'): {},
        ('other', 'другое'): {},
    },
    ('components', 'компоненты'): {
        ('CD, DVD, BD drives', 'CD, DVD, BD приводы'): {
            ('CD', 'CD'): {},
            ('DVD', 'DVD'): {},
            ('BD', 'BD'): {},
            ('other', 'другое'): {},
        },
        ('cases', 'корпусы'): {},
        ('cooling, fans', 'вентиляторы'): {},
        ('CPUs', 'процессоры'): {
            ('intel', 'intel'): {},
            ('AMD', 'AMD'): {},
            ('other', 'другое'): {},
        },
        ('hard drives', 'жесткие диски'): {
            ('IDE', 'IDE'): {},
            ('laptop', 'ноутбуки'): {},
            ('SATA', 'SATA'): {},
            ('SCSI', 'SCSI'): {},
            ('SSD', 'SSD'): {},
            ('other', 'другое'): {},
        },
        ('memory', 'память'): {
            ('desktop', 'десктопы'): {},
            ('laptop', 'ноутбуки'): {},
            ('server', 'серверы'): {},
            ('other', 'другое'): {},
        },
        ('motherboards', 'материнские платы'): {
            ('AMD', 'AMD'): {},
            ('asus', 'asus'): {},
            ('intel', 'intel'): {},
            ('other', 'другое'): {},
        },
        ('other PCI cards', 'другие PCI карты'): {},
        ('power supplies', 'источники питания'): {},
        ('sound cards', 'звуковые карты'): {},
        ('video cards', 'видео карты'): {
            ('AGP', 'AGP'): {},
            ('PCI Express', 'PCI Express'): {},
            ('other', 'другое'): {},
        },
    },
    ('furniture', 'мебель'): {
        ('desks', 'столы'): {},
        ('chairs', 'кресла, стулья'): {},
        ('other', 'другое'): {},
    },
    ('desktops', 'компьютеры десктоп'): {},
    ('external storage', 'внешние накопители'): {
        ('hard drives', 'жесткие диски'): {},
        ('USB flash memory', 'USB флэш память'): {},
        ('other', 'другое'): {},
    },
    ('laptops, netbooks, acc.', 'ноутбуки, нетбуки, акс.'): {
        ('accessories, parts', 'аксессуары, части'): {
            ('bags', 'сумки'): {},
            ('batteries', 'батареи'): laptop_brands,
            ('docking stations', 'док-станция'): {},
            ('memory', 'память'): {},
            ('extension cards', 'платы расширения'): {},
            ('power adaptors', 'адаптеры питания'): laptop_brands,
            ('anti-theft, locks', 'анти-вор, замки'): {},
            ('cooling pads', 'подставки охлаждения'): {},
            ('mounts', 'держатели'): {},
            ('lights', 'освещение'): {},
            ('other', 'другое'): {},
        },
        ('laptops, netbooks', 'ноутбуки, нетбуки'): laptop_brands,
    },
    ('monitors', 'мониторы'): {
        ('acer', 'acer'): {},
        ('asus', 'asus'): {},
        ('dell', 'dell'): {},
        ('hp', 'hp'): {},
        ('LG', 'LG'): {},
        ('nec', 'nec'): {},
        ('samsung', 'samsung'): {},
        ('ViewSonic', 'ViewSonic'): {},
        ('other', 'другое'): {},
    },
    ('networking', 'сети'): {
        ('hubs, switches', 'хабы, переключатели'): {},
        ('modems', 'модемы'): {},
        ('network cards', 'сетевые карты'): {},
        ('routers, firewalls', 'раутеры, firewalls'): {},
        ('wireless', 'беспроводные'): {
            ('adaptors', 'адаптеры'): {},
            ('antennas', 'антенны'): {},
            ('cards', 'карты, платы'): {},
            ('routers', 'раутеры'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('handhelds, tablets', 'кпк, планшеты'): {
        ('accessories', 'аксессуары'): {},
        ('handhelds', 'кпк'): {},
        ('tablets', 'планшеты'): {
            ('acer', 'acer'): {},
            ('apple', 'apple'): {},
            ('asus', 'asus'): {},
            ('blackberry', 'blackberry'): {},
            ('hp', 'hp'): {},
            ('htc', 'htc'): {},
            ('motorola', 'motorola'): {},
            ('samsung', 'samsung'): {},
            ('toshiba', 'toshiba'): {},
            ('dell', 'dell'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('printers', 'принтеры'): {
        ('accessories, supplies', 'аксессуары, расходные'): {
            ('canon', 'canon'): {},
            ('brother', 'brother'): {},
            ('dell', 'dell'): {},
            ('epson', 'epson'): {},
            ('hp', 'hp'): {},
            ('lexmark', 'lexmark'): {},
            ('oki', 'oki'): {},
            ('samsung', 'samsung'): {},
            ('other', 'другое'): {},
        },
        ('canon', 'canon'): {},
        ('brother', 'brother'): {},
        ('dell', 'dell'): {},
        ('epson', 'epson'): {},
        ('hp', 'hp'): {},
        ('lexmark', 'lexmark'): {},
        ('oki', 'oki'): {},
        ('samsung', 'samsung'): {},
        ('other', 'другое'): {},
    },
    ('servers', 'серверы'): {},
    ('other', 'другое'): {},
}
}
