# -*- coding: utf-8 -*-
"""'electronics' part of product categories dictionary.

Must hold subcategories of 'electronics'
category in the form of python dictionary data type.

"""
electronics = {('electronics', 'электроника'): {
    ('batteries', 'батареи'): {
        ('rechargeable', 'многоразовые'): {},
        ('single use', 'одноразовые'): {},
        ('chargers', 'зарядные устройства'): {},
        ('other', 'другое'): {},
    },
    ('digital cameras', 'цифровые камеры'): {
        ('bags, cases', 'сумки, футляры'): {},
        ('filters', 'фильтры'): {},
        ('flashes, lighting', 'вспышки, освещение'): {},
        ('memory cards', 'память'): {},
        ('tripods', 'треноги, штативы'): {},
        ('cameras', 'камеры'): {
            ('canon', 'canon'): {
                ('accessories', 'аксессуары'): {},
                ('digital SLR', 'зеркальные'): {},
                ('point and shoot', 'компактные'): {},
                ('other', 'другое'): {},
            },
            ('nikon', 'nikon'): {
                ('accessories', 'аксессуары'): {},
                ('digital SLR', 'зеркальные'): {},
                ('point and shoot', 'компактные'): {},
                ('other', 'другое'): {},
            },
            ('olympus', 'olympus'): {
                ('accessories', 'аксессуары'): {},
                ('digital SLR', 'зеркальные'): {},
                ('point and shoot', 'компактные'): {},
                ('other', 'другое'): {},
            },
            ('sony', 'sony'): {
                ('accessories', 'аксессуары'): {},
                ('digital SLR', 'зеркальные'): {},
                ('point and shoot', 'компактные'): {},
                ('other', 'другое'): {},
            },
            ('kodak', 'kodak'): {
                ('accessories', 'аксессуары'): {},
                ('digital SLR', 'зеркальные'): {},
                ('point and shoot', 'компактные'): {},
                ('other', 'другое'): {},
            },
            ('fujifilm', 'fujifilm'): {
                ('accessories', 'аксессуары'): {},
                ('digital SLR', 'зеркальные'): {},
                ('point and shoot', 'компактные'): {},
                ('other', 'другое'): {},
            },
            ('panasonic', 'panasonic'): {
                ('accessories', 'аксессуары'): {},
                ('digital SLR', 'зеркальные'): {},
                ('point and shoot', 'компактные'): {},
                ('other', 'другое'): {},
            },
            ('pentax', 'pentax'): {
                ('accessories', 'аксессуары'): {},
                ('digital SLR', 'зеркальные'): {},
                ('point and shoot', 'компактные'): {},
                ('other', 'другое'): {},
            },
            ('samsung', 'samsung'): {
                ('accessories', 'аксессуары'): {},
                ('digital SLR', 'зеркальные'): {},
                ('point and shoot', 'компактные'): {},
                ('other', 'другое'): {},
            },
            ('other', 'другое'): {},
        },
    },
    ('electronic gadgets', 'устройства'): {
        ('adaptors, chargers', 'адаптеры, зарядки'): {},
        ('digital photo frames', 'цифровые рамки'): {},
        ('torches', 'фонарики'): {},
        ('air purifiers', 'очистители воздуха'): {},
        ('breathalyzers', 'индикаторы алкоголя дыхания'): {},
        ('calculators', 'калькуляторы'): {},
        ('dictionaries', 'словари'): {},
        ('clocks', 'часы'): {},
        ('radios', 'радио'): {},
        ('eBook readers', 'чтение книг'): {},
        ('laser pointers', 'лазерные указки'): {},
        ('metal detectors', 'металлодетекторы'): {},
        ('surveillance', 'наблюдение'): {},
        ('timers', 'таймеры'): {},
        ('dictaphones', 'диктафоны'): {},
        ('voltage converters', 'преобразователи'): {},
        ('weather devices', 'погодные устройства'): {},
        ('other', 'другое'): {},
    },
    ('home audio', 'домашнее аудио'): {
        ('amplifiers', 'усилители'): {},
        ('CD players', 'CD проигрователи'): {},
        ('crossovers', 'кроссоверы'): {},
        ('equalizers', 'эквалайзеры'): {},
        ('karaoke', 'караоке'): {},
        ('radios', 'радио'): {},
        ('receivers', 'ресиверы'): {},
        ('speakers', 'колонки'): {},
        ('headphones', 'наушники'): {},
        ('subwoofers', 'сабвуферы'): {},
        ('tuners', 'тюнеры'): {},
        ('turntables', 'вертушки'): {},
        ('other', 'другое'): {},
    },
    ('home video', 'домашнее видео'): {
        ('DVD', 'DVD'): {},
        ('BD', 'BD'): {},
        ('Projectors, screens', 'проекторы, экраны'): {},
        ('TVs', 'телевизоры, аксессуоры'): {
            ('accessories', 'аксессуары'): {
                ('antennas', 'антенны'): {},
                ('cables, adaptors', 'кабели, адаптеры'): {},
                ('remotes', 'пульты'): {},
                ('satellite equipment', 'спутниковое оборудование'): {},
                ('TV furniture', 'мебель'): {},
                ('wall brackets', 'крепежи на стену'): {},
                ('other', 'другое'): {},
            },
            ('TV sets', 'телевизоры'): {
                ('hitachi', 'hitachi'): {},
                ('jvc', 'jvc'): {},
                ('LG', 'LG'): {},
                ('mitsubishi', 'mitsubishi'): {},
                ('nec', 'nec'): {},
                ('panasonic', 'panasonic'): {},
                ('philips', 'philips'): {},
                ('samsung', 'samsung'): {},
                ('sharp', 'sharp'): {},
                ('sony', 'sony'): {},
                ('supersonic', 'supersonic'): {},
                #('sylvania', 'sylvania'): {},
                ('toshiba', 'toshiba'): {},
                ('other', 'другое'): {},
            },
        },
    },
    ('iPod, MP3', 'iPod, MP3'): {
        ('iPod', 'iPod'): {},
        ('MP3 players', 'MP3 плееры'): {},
        ('accessories', 'аксессуары'): {
            ('cables', 'кабели'): {},
            ('armbands', 'нарукавные чехлы'): {},
            ('bluetooth adapters', 'адаптеры bluetooth'): {},
            ('car kits', 'для машины'): {},
            ('cases', 'чехлы, кейсы'): {},
            ('docks, cradles', 'доки, гнезда'): {},
            ('FM transmitters', 'FM транзмитеры'): {},
            ('headphones', 'наушники'): {},
            ('remotes', 'пульты'): {},
            ('batteries', 'батареи'): {},
            ('screen protectors', 'защита экрана'): {},
            ('skins', 'скины'): {},
            ('socks', 'мешочки, носки'): {},
            ('speakers', 'колонки'): {},
            ('wall chargers', 'зарядные устройства'): {},
            ('parts', 'запчасти'): {},
            ('other', 'другое'): {},
        },
    },
    ('GPS', 'GPS'): {
        ('automotive', 'автомобильные'): {},
        ('outdoor', 'аутдор'): {},
        ('marine', 'морские'): {},
        ('tracking devices', 'устройства слежения'): {},
        ('software, maps', 'софт, карты'): {},
        ('accessories', 'аксессуары'): {},
        ('other', 'другое'): {},
    },
    ('optics', 'оптика'): {
        ('binoculars', 'бинокли'): {},
        ('telescopes', 'телескопы'): {},
        ('other', 'другое'): {},
    },
    ('radio', 'радио'): {
        ('amateur', 'любительское'): {
            ('amplifiers', 'усилители'): {},
            ('antennas', 'антенны'): {},
            ('batteries, chargers', 'батареи, зарядки'): {},
            ('cables, adapters', 'кабели, адаптеры'): {},
            ('headsets', 'наушники'): {},
            ('microphones', 'микрофоны'): {},
            ('oscillators, filters', 'осциляторы, фильтры'): {},
            ('power supplies', 'источники питания'): {},
            ('receivers', 'ресиверы'): {},
            ('speakers', 'колонки'): {},
            ('transceivers', 'приемопередатчики'): {},
            ('transmitters', 'передатчики'): {},
            ('accessories', 'аксессуары'): {},
            ('parts', 'запчасти'): {},
            ('other', 'другое'): {},
        },
        ('commercial', 'коммерческое'): {},
        ('2-Way Radios, Walkie Talkies', 'переговорные устройства'): {},
        ('marine', 'морские'): {},
        ('scanners', 'сканеры'): {},
        ('other', 'другое'): {},
    },
    ('telephones, fax', 'телефон, факс'): {
        ('answering machines', 'автоответчики'): {},
        ('corded phones', 'телефоны проводные'): {},
        ('cordless phones', 'телефоны беспроводные'): {},
        ('fax machines', 'факсы'): {},
        ('other', 'другое'): {},
    },
    ('video cameras', 'видео камеры'): {
        ('canon', 'canon'): {},
        ('jvc', 'jvc'): {},
        ('panasonic', 'panasonic'): {},
        ('samsung', 'samsung'): {},
        ('sony', 'sony'): {},
        ('other', 'другое'): {},
    },
}
}
