# -*- coding: utf-8 -*-
"""'health, beauty' part of product categories dictionary.

Must hold subcategories of 'health, beauty'
category in the form of python dictionary data type.

"""
#('body, bath',): {
#('nutrition, supplements',): {
#('perfume',): {
#('hair care, shaving',): {
#('hand, foot care',): {
#('makeup',): {
#('massage',): {
#('medical, aids, disability',): {
#('skin care',): {
health_beauty = {('health, beauty', 'красота, здоровье'): {
    ('body, bath', 'тело, купание'): {
        ('bath kits', 'наборы для ванн'): {},
        ('powders', 'присыпки'): {},
        ('body washes, shower gels', 'гель для душа'): {},
        ('bubble baths', 'пенна для ванн'): {},
        ('kids', 'детское'): {},
        ('deodorants', 'деодоранты'): {},
        ('lotions', 'лосьоны'): {},
        ('salts', 'соли'): {},
        ('scrubs', 'скрабы'): {},
        ('soaps', 'мыло'): {},
        ('other', 'другое'): {},
    },
    ('nutrition, supplements', 'питание, добавки'): {
        ('detox, cleanse', 'детокс, очистка'): {},
        ('energy supplements', 'энергетики'): {},
        ('herbal', 'травы, растительное'): {},
        ('brain, memory', 'мозг, память'): {},
        ('cosmetic', 'косметическое'): {},
        ('relaxation, sleep', 'релаксация, сон'): {},
        ('weight loss', 'похудание'): {},
        ('womens health', 'женское здоровье'): {},
        ('mens health', 'мужское здоровье'): {},
        ('vitamins, minerals', 'витамины, минералы'): {},
        ('other', 'другое'): {},
    },
    ('perfume', 'духи, ароматы'): {
        ('women', 'женщины'): {},
        ('men', 'мужчины'): {},
        ('unisex', 'унисекс'): {},
    },
    ('hair care, shaving', 'уход за волосами, бритье'): {
        ('hair care products', 'продукты для волос'): {
            ('conditioner', 'кондиционер'): {},
            ('hair color', 'краска'): {},
            ('hair loss', 'от потери волос'): {},
            ('shampoo', 'шампунь'): {},
            ('damage treatments', 'поврежденные волосы'): {},
            ('perms', 'химзавивка'): {},
            ('styling', 'стайлинг'): {
                ('gel', 'гель'): {},
                ('mousse', 'мусс'): {},
                ('spray', 'спрей'): {},
                ('wax', 'воск'): {},
                ('other', 'другое'): {},
            },
            ('other', 'другое'): {},
        },
        ('hair tools', 'инструмент для волос'): {
            ('braiders', 'брейдеры'): {},
            ('clippers', 'для стрижки'): {},
            ('brushes, combs', 'расчески, щетки'): {},
            ('dryers', 'фены'): {},
            ('curlers', 'завивка'): {},
            ('scissors', 'ножницы'): {},
            ('straighteners', 'выпрямители'): {},
            ('other', 'другое'): {},
        },
        ('accessories', 'аксессуары'): {
            ('clips', 'зажимы'): {},
            ('hair extensions', 'накладные волосы'): {},
            ('hair ties, bands', 'резинки, повязки'): {},
            ('wigs', 'парики'): {},
            ('other', 'другое'): {},
        },
        ('shaving, hair removal', 'бритье, эпиляция'): {
            ('clippers, trimmers', 'клиперы, триммеры'): {},
            ('creams, lotions', 'кремы, лосьоны'): {},
            ('electric shavers', 'электробритвы'): {},
            ('epilators', 'эпиляторы'): {},
            ('laser hair removal', 'лазерная эпиляция'): {},
            ('razors, blades', 'бритвы, лезвия'): {},
            ('scissors', 'ножницы'): {},
            ('tweezers', 'щипчики'): {},
            ('waxing', 'воск'): {},
            ('other', 'другое'): {},
        },
    },
    ('hand, foot care', 'уход за руками, ногами'): {
        ('foot spas', 'ножные ванны'): {},
        ('hand creams', 'кремы'): {},
        ('nail care', 'уход за ногтями'): {
            ('cutting, filing', 'резка, шлифовка'): {},
            ('nail art', 'дизайн ногтей'): {},
            ('nail polish', 'лак'): {},
            ('nails, tips', 'накладные ногти'): {},
            ('manicure  kits', 'наборы маникюрные'): {},
            ('pedicure kits', 'наборы педикюрные'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('makeup', 'макияж'): {
        ('bags, cases', 'сумки, футляры'): {},
        ('body', 'тело'): {},
        ('eyes', 'глаза'): {
            ('brow enhancers', 'брови'): {},
            ('eyeliner', 'подводка'): {},
            ('eye shadow', 'тени'): {},
            ('false eyelashes', 'накладные ресницы'): {},
            ('mascara', 'тушь'): {},
            ('removers', 'удаление косметики'): {},
            ('kits', 'наборы'): {},
            ('other', 'другое'): {},
        },
        ('face', 'лицо'): {
            ('blush', 'румяна'): {},
            ('bronzers, highlighters', 'тональный крем'): {},
            ('concealer', 'коректор'): {},
            ('face powder', 'пудра'): {},
            ('foundation', 'база'): {
                ('cream', 'крем'): {},
                ('liquid', 'жидкое'): {},
                ('mousse', 'мусс'): {},
                ('other', 'другое'): {},
            },
            ('removers', 'удаление косметики'): {},
            ('kits', 'наборы'): {},
            ('other', 'другое'): {},
        },
        ('lips', 'губы'): {
            ('balm', 'бальзам'): {},
            ('gloss', 'блеск'): {},
            ('liner', 'карандаш'): {},
            ('plumper', 'плампер'): {},
            ('lipstick', 'помада'): {},
            ('removers', 'удаление косметики'): {},
            ('kits', 'наборы'): {},
            ('other', 'другое'): {},
        },
        ('tools, accessories', 'инструмент, аксессуары'): {
            ('brushes, applicators', 'кисти, аппликаторы'): {
                ('blush', 'румяна'): {},
                ('concealer', 'коректор'): {},
                ('eye shadow', 'тени'): {},
                ('eyeliner', 'подводка'): {},
                ('foundation', 'база'): {},
                ('kabuki', 'кабуки'): {},
                ('lip brushes', 'для губ'): {},
                ('powder', 'пудра'): {},
                ('kits', 'наборы'): {},
                ('other', 'другое'): {},
            },
            ('compact mirrors', 'зеркальца'): {},
            ('puffs, sponges, wedges', 'спонж'): {},
            ('sharpeners', 'точилки'): {},
            ('other', 'другое'): {},
        },
        ('kits', 'наборы'): {},
    },
    ('massage', 'массаж'): {
        ('chairs', 'кресла'): {},
        ('massagers', 'массажеры'): {
            ('back', 'спина'): {},
            ('foot', 'ступни'): {},
            ('full body', 'тело'): {},
            ('head, neck', 'голова, шея'): {},
            ('other', 'другое'): {},
        },
        ('oils', 'масла'): {},
        ('pillows', 'подушки'): {},
        ('tables', 'столы'): {},
        ('other', 'другое'): {},
    },
    ('medical, aids, disability', 'медицинские, медтехника'): {
        ('cellulite treatment', 'лечение целлюлита'): {},
        ('bathroom safety', 'туалет, купание'): {},
        ('braces, supports', 'шины, поддержки'): {},
        ('feminine hygiene', 'женская гигиена'): {},
        ('first aid', 'апптечки'): {},
        ('hearing assistance', 'слуховые аппараты'): {},
        ('incontinence aids', 'недержание'): {},
        ('mobility aids', 'передвижение'): {},
        ('positioning equipment', 'фиксаторы'): {},
        ('sleeping aids', 'сон'): {},
        ('other', 'другое'): {},
    },
    ('skin care', 'уход за кожей'): {
        ('acne, blemish control', 'контроль прыщей'): {},
        ('anti aging products', 'от старения'): {},
        ('cleansers', 'очистка'): {},
        ('exfoliators, scrubs', 'скрабы'): {},
        ('eye creams, gels', 'кремы, гели для глаз'): {},
        ('eye masks', 'маски для глаз'): {},
        ('lightening cream', 'осветляющие кремы'): {},
        ('makeup removers', 'удаление косметики'): {},
        ('masks, peels', 'маски'): {},
        ('mens', 'мужская'): {},
        ('moisturizers', 'увлажнение'): {},
        ('night cream', 'ночные кремы'): {},
        ('sun care', 'солнечные средства'): {},
        ('toners', 'тонеры'): {},
        ('kits', 'наборы'): {},
        ('other', 'другое'): {},
    },
}
}
