# -*- coding: utf-8 -*-
"""'Mobile phones, devices' part of product categories dictionary.

Must hold subcategories of 'Mobile phones, devices'
category in the form of python dictionary data type.

"""

mobile_phones_devices = {('mobile phones, PDAs', 'мобильные телефоны, устройства'): {
    ('apple', 'apple'): {
        ('devices', 'устройства'): {},
        ('accessories', 'аксессуары'): {
            ('batteries', 'батареи'): {},
            ('cables, adapters', 'кабели, адаптеры'): {},
            ('car kits', 'для машины'): {},
            ('cases, covers, skins', 'кейсы, скины, чехлы'): {},
            ('chargers', 'зарядные устройства'): {},
            ('charms', 'медальоны'): {},
            ('faceplates', 'лицевые панели'): {},
            ('headsets', 'наушники'): {},
            ('memory cards', 'память'): {},
            ('mounts, holders', 'крепежи, держатели'): {},
            ('screen protectors', 'защита экрана'): {},
            ('straps', 'ремешки'): {},
            ('styluses', 'стилус'): {},
            ('other', 'другое'): {},
        },
        ('parts', 'запчасти'): {},
        ('devices for parts', 'устройства на запчасти'): {},
        ('other', 'другое'): {},
    },
    ('HTC', 'HTC'): {
        ('devices', 'устройства'): {},
        ('accessories', 'аксессуары'): {
            ('batteries', 'батареи'): {},
            ('cables, adapters', 'кабели, адаптеры'): {},
            ('car kits', 'для машины'): {},
            ('cases, covers, skins', 'кейсы, скины, чехлы'): {},
            ('chargers', 'зарядные устройства'): {},
            ('charms', 'медальоны'): {},
            ('faceplates', 'лицевые панели'): {},
            ('headsets', 'наушники'): {},
            ('memory cards', 'память'): {},
            ('mounts, holders', 'крепежи, держатели'): {},
            ('screen protectors', 'защита экрана'): {},
            ('straps', 'ремешки'): {},
            ('styluses', 'стилус'): {},
            ('other', 'другое'): {},
        },
        ('parts', 'запчасти'): {},
        ('devices for parts', 'устройства на запчасти'): {},
        ('other', 'другое'): {},
    },
    ('LG', 'LG'): {
        ('devices', 'устройства'): {},
        ('accessories', 'аксессуары'): {
            ('batteries', 'батареи'): {},
            ('cables, adapters', 'кабели, адаптеры'): {},
            ('car kits', 'для машины'): {},
            ('cases, covers, skins', 'кейсы, скины, чехлы'): {},
            ('chargers', 'зарядные устройства'): {},
            ('charms', 'медальоны'): {},
            ('faceplates', 'лицевые панели'): {},
            ('headsets', 'наушники'): {},
            ('memory cards', 'память'): {},
            ('mounts, holders', 'крепежи, держатели'): {},
            ('screen protectors', 'защита экрана'): {},
            ('straps', 'ремешки'): {},
            ('styluses', 'стилус'): {},
            ('other', 'другое'): {},
        },
        ('parts', 'запчасти'): {},
        ('devices for parts', 'устройства на запчасти'): {},
        ('other', 'другое'): {},
    },
    ('lenovo', 'lenovo'): {
        ('devices', 'устройства'): {},
        ('accessories', 'аксессуары'): {
            ('batteries', 'батареи'): {},
            ('cables, adapters', 'кабели, адаптеры'): {},
            ('car kits', 'для машины'): {},
            ('cases, covers, skins', 'кейсы, скины, чехлы'): {},
            ('chargers', 'зарядные устройства'): {},
            ('charms', 'медальоны'): {},
            ('faceplates', 'лицевые панели'): {},
            ('headsets', 'наушники'): {},
            ('memory cards', 'память'): {},
            ('mounts, holders', 'крепежи, держатели'): {},
            ('screen protectors', 'защита экрана'): {},
            ('straps', 'ремешки'): {},
            ('styluses', 'стилус'): {},
            ('other', 'другое'): {},
        },
        ('parts', 'запчасти'): {},
        ('devices for parts', 'устройства на запчасти'): {},
        ('other', 'другое'): {},
    },
    ('motorola', 'motorola'): {
        ('devices', 'устройства'): {},
        ('accessories', 'аксессуары'): {
            ('batteries', 'батареи'): {},
            ('cables, adapters', 'кабели, адаптеры'): {},
            ('car kits', 'для машины'): {},
            ('cases, covers, skins', 'кейсы, скины, чехлы'): {},
            ('chargers', 'зарядные устройства'): {},
            ('charms', 'медальоны'): {},
            ('faceplates', 'лицевые панели'): {},
            ('headsets', 'наушники'): {},
            ('memory cards', 'память'): {},
            ('mounts, holders', 'крепежи, держатели'): {},
            ('screen protectors', 'защита экрана'): {},
            ('straps', 'ремешки'): {},
            ('styluses', 'стилус'): {},
            ('other', 'другое'): {},
        },
        ('parts', 'запчасти'): {},
        ('devices for parts', 'устройства на запчасти'): {},
        ('other', 'другое'): {},
    },
    ('nokia', 'nokia'): {
        ('devices', 'устройства'): {},
        ('accessories', 'аксессуары'): {
            ('batteries', 'батареи'): {},
            ('cables, adapters', 'кабели, адаптеры'): {},
            ('car kits', 'для машины'): {},
            ('cases, covers, skins', 'кейсы, скины, чехлы'): {},
            ('chargers', 'зарядные устройства'): {},
            ('charms', 'медальоны'): {},
            ('faceplates', 'лицевые панели'): {},
            ('headsets', 'наушники'): {},
            ('memory cards', 'память'): {},
            ('mounts, holders', 'крепежи, держатели'): {},
            ('screen protectors', 'защита экрана'): {},
            ('straps', 'ремешки'): {},
            ('styluses', 'стилус'): {},
            ('other', 'другое'): {},
        },
        ('parts', 'запчасти'): {},
        ('devices for parts', 'устройства на запчасти'): {},
        ('other', 'другое'): {},
    },
    ('samsung', 'samsung'): {
        ('devices', 'устройства'): {},
        ('accessories', 'аксессуары'): {
            ('batteries', 'батареи'): {},
            ('cables, adapters', 'кабели, адаптеры'): {},
            ('car kits', 'для машины'): {},
            ('cases, covers, skins', 'кейсы, скины, чехлы'): {},
            ('chargers', 'зарядные устройства'): {},
            ('charms', 'медальоны'): {},
            ('faceplates', 'лицевые панели'): {},
            ('headsets', 'наушники'): {},
            ('memory cards', 'память'): {},
            ('mounts, holders', 'крепежи, держатели'): {},
            ('screen protectors', 'защита экрана'): {},
            ('straps', 'ремешки'): {},
            ('styluses', 'стилус'): {},
            ('other', 'другое'): {},
        },
        ('parts', 'запчасти'): {},
        ('devices for parts', 'устройства на запчасти'): {},
        ('other', 'другое'): {},
    },
    ('Sony Ericsson', 'Sony Ericsson'): {
        ('devices', 'устройства'): {},
        ('accessories', 'аксессуары'): {
            ('batteries', 'батареи'): {},
            ('cables, adapters', 'кабели, адаптеры'): {},
            ('car kits', 'для машины'): {},
            ('cases, covers, skins', 'кейсы, скины, чехлы'): {},
            ('chargers', 'зарядные устройства'): {},
            ('charms', 'медальоны'): {},
            ('faceplates', 'лицевые панели'): {},
            ('headsets', 'наушники'): {},
            ('memory cards', 'память'): {},
            ('mounts, holders', 'крепежи, держатели'): {},
            ('screen protectors', 'защита экрана'): {},
            ('straps', 'ремешки'): {},
            ('styluses', 'стилус'): {},
            ('other', 'другое'): {},
        },
        ('parts', 'запчасти'): {},
        ('devices for parts', 'устройства на запчасти'): {},
        ('other', 'другое'): {},
    },
    ('other brands', 'другие бренды'): {
        ('devices', 'устройства'): {},
        ('accessories', 'аксессуары'): {
            ('batteries', 'батареи'): {},
            ('cables, adapters', 'кабели, адаптеры'): {},
            ('car kits', 'для машины'): {},
            ('cases, covers, skins', 'кейсы, скины, чехлы'): {},
            ('chargers', 'зарядные устройства'): {},
            ('charms', 'медальоны'): {},
            ('faceplates', 'лицевые панели'): {},
            ('headsets', 'наушники'): {},
            ('memory cards', 'память'): {},
            ('mounts, holders', 'крепежи, держатели'): {},
            ('screen protectors', 'защита экрана'): {},
            ('straps', 'ремешки'): {},
            ('styluses', 'стилус'): {},
            ('other', 'другое'): {},
        },
        ('parts', 'запчасти'): {},
        ('devices for parts', 'устройства на запчасти'): {},
        ('other', 'другое'): {},
    },
    ('other', 'другое'): {},
    #phones
    #smartphones
    #display phones
    #('PDAs, pocket PCs',): {
}}
