# -*- coding: utf-8 -*-
"""'musical instruments' part of product categories dictionary.

Must hold subcategories of 'musical instruments'
category in the form of python dictionary data type.

"""
musical_instruments = {('musical instruments', 'музыкальные инструменты'): {
    ('accordion', 'аккордеон'): {},
    ('accessories', 'аксессуары'): {
        ('metronomes', 'метрономы'): {},
        ('music stands', 'пюпитр'): {},
        ('tuners', 'механизм настройки'): {},
        ('other', 'другое'): {},
    },
    ('instruction books, videos', 'самоучители'): {},
    ('brass', 'духовые медные'): {
        ('baritone, tuba', 'баритон, туба'): {},
        ('bugle', 'горн'): {},
        ('euphonium', 'эуфониум'): {},
        ('flugelhorn', 'флюгельгорн'): {},
        ('french horn', 'валторна'): {},
        ('trombone', 'тромбон'): {},
        ('trumpet', 'труба'): {},
        ('cornet', 'корнет'): {},
        ('sousaphone', 'сузафон'): {},
        ('parts, accessories', 'запчасти, аксессуары'): {},
        ('other', 'другое'): {},
    },
    ('percussion', 'ударные'): {
        ('bells', 'колокола'): {},
        ('cymbals', 'тарелки'): {
            ('crash', 'crash'): {},
            ('ride', 'ride'): {},
            ('hi-hat', 'hi-hat'): {},
            ('splash', 'splash'): {},
            ('sets', 'наборы'): {},
            ('other', 'другое'): {},
        },
        ('drums', 'барабаны'): {
            ('bass', 'bass'): {},
            ('snare', 'snare'): {},
            ('toms', 'toms'): {},
            ('world', 'world'): {},
            ('sets', 'наборы'): {},
            ('stools, thrones', 'стулья'): {},
            ('other', 'другое'): {},
        },
        ('tambourines', 'бубен'): {},
        ('xylophones', 'ксилофоны'): {},
        ('parts, accessories', 'запчасти, аксессуары'): {
            ('bags, cases', 'сумки, кейсы'): {},
            ('heads', 'мембраны'): {},
            ('mounts', 'держатели'): {},
            ('pedals', 'педали'): {},
            ('stands', 'стойки'): {},
            ('sticks, brushes', 'палочки, щетки'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('guitar', 'гитара'): {
        ('acoustic', 'акустика'): {},
        ('acoustic electric', 'акустика электро'): {},
        ('bass', 'басс'): {},
        ('electric', 'электро'): {},
        ('guitar amplifiers', 'усилители'): {},
        ('parts, accessories', 'запчасти, аксессуары'): {
            ('cables', 'кабели'): {},
            ('cases', 'чехлы, кейсы'): {},
            ('effects pedals', 'педали еффектов'): {
                ('bass', 'bass'): {},
                ('chorus', 'chorus'): {},
                ('compressors, sustainers', 'compressors, sustainers'): {},
                ('delay, echo, reverb', 'delay, echo, reverb'): {},
                ('distortion, overdrive', 'distortion, overdrive'): {},
                ('filter, modulation', 'filter, modulation'): {},
                ('flangers', 'flangers'): {},
                ('fuzz', 'fuzz'): {},
                ('multi-effects', 'multi-effects'): {},
                ('phasers, shifters', 'phasers, shifters'): {},
                ('wah, volume', 'wah, volume'): {},
                ('other', 'другое'): {},
            },
            ('guitar parts', 'гитарные части'): {
                ('bodies', 'bodies'): {},
                ('bridges', 'bridges'): {},
                ('capacitors', 'capacitors'): {},
                ('knobs, jacks, switches', 'knobs, jacks, switches'): {},
                ('necks', 'necks'): {},
                ('nuts', 'nuts'): {},
                ('pickguards', 'pickguards'): {},
                ('pickups', 'pickups'): {},
                ('plates', 'plates'): {},
                ('saddles', 'saddles'): {},
                ('tuning pegs', 'tuning pegs'): {},
                ('other', 'другое'): {},
            },
            ('picks', 'медиаторы'): {},
            ('stands, hangers', 'стойки, вешалки'): {},
            ('straps', 'ремни'): {},
            ('strings', 'струны'): {},
            ('power supplies', 'источники питания'): {},
            ('tuners', 'механизм настройки'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('keyboards, piano', 'синтезаторы, пианино'): {
        ('digital pianos', 'электронные пианино'): {},
        ('grand pianos', 'рояли'): {},
        ('keyboards', 'синтезаторы'): {},
        ('organs', 'органы'): {},
        ('upright pianos', 'пианино'): {},
        ('other', 'другое'): {},
    },
    ('sheet music', 'ноты'): {
        ('blues, jazz', 'блюз, джаз'): {},
        ('christmas', 'рождество'): {},
        ('kids', 'детское'): {},
        ('classical', 'классика'): {},
        ('country', 'кантри'): {},
        ('movies', 'из фильмов'): {},
        ('rock', 'рок'): {},
        ('pop', 'поп'): {},
        ('vocal', 'вокальные'): {},
        ('other', 'другое'): {},
    },
    ('song books', 'сборники песен'): {
        ('accordion', 'аккордеон'): {},
        ('brass, woodwind', 'духовые'): {},
        ('guitar', 'гитара'): {},
        ('piano', 'пианино'): {},
        ('string instruments', 'струнные'): {},
        ('other', 'другое'): {},
    },
    ('string instruments', 'струнные'): {
        ('banjo', 'банжо'): {},
        ('cello', 'виолончель'): {},
        ('double bass', 'контрабас'): {},
        ('harp', 'арфа'): {},
        ('mandolin', 'мандолина'): {},
        ('ukulele', 'гавайская гитара'): {},
        ('viola', 'альт'): {},
        ('violin', 'скрипка'): {},
        ('parts, accessories', 'запчасти, аксессуары'): {
            ('strings', 'струны'): {},
            ('bows', 'смычки'): {},
            ('rests', 'подбородник, мостик'): {},
            ('rosin', 'канифоль'): {},
            ('cases', 'чехлы, кейсы'): {},
            ('pegs', 'колок'): {},
            ('tuners', 'механизм настройки'): {},
            ('mutes', 'глушилки'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('wind instruments', 'деревянные духовые'): {
        ('bassoon', 'фагот'): {},
        ('clarinet', 'кларнет'): {},
        ('flute', 'флейта'): {},
        ('oboe', 'гобой'): {},
        ('saxophone', 'саксофон'): {},
        ('parts, accessories', 'запчасти, аксессуары'): {},
        ('other', 'другое'): {},
    },
    ('other', 'другое'): {},
}
}
