# -*- coding: utf-8 -*-
"""'Baby, kids' part of product categories dictionary.

Must hold subcategories of 'Baby, kids'
category in the form of python dictionary data type.

"""

baby_kids_ages = {
    ('newborn', 'новорожденные'): {},
    ('3-6 months', '3-6 месяцев'): {},
    ('6-9 months', '6-9 месяцев'): {},
    ('9-12 months', '9-12 месяцев'): {},
    ('12-18 months', '12-18 месяцев'): {},
    ('18-24 months', '18-24 месяцев'): {},
}
baby_kids = {('baby, kids', 'дети, младенцы'): {
    ('bathing, grooming', 'купание, уход'): {
        ('bath seats, supports', 'сидения, поддержки'): {},
        ('bath toys', 'игрушки для ванн'): {},
        ('baths', 'ванны'): {},
        ('grooming', 'уход'): {},
        ('towels, cloths', 'полотенца'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('beds, bedding', 'кроватки, постели'): {
        ('cots, cribs, bassinets', 'кроватки, колыбели'): {},
        ('blankets', 'одеяла'): {},
        ('covers', 'покрывала'): {},
        ('comforters, duvets', 'стеганные одеяла'): {},
        ('bed linen', 'постельное белье'): {},
        ('mattresses', 'матрасы'): {},
        ('pillows', 'подушки'): {},
        ('sleeping bags', 'спальные мешки'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('car seats', 'автокресла'): {},
    ('clothing', 'одежда'): {
        ('girls', 'девочки'): {
            ('accessories', 'аксессуары'): baby_kids_ages,
            ('dresses', 'платья, сарафаны'): baby_kids_ages,
            ('footwear', 'обувь'): baby_kids_ages,
            ('hats', 'головные уборы'): baby_kids_ages,
            ('light bottoms', 'легкий низ'): baby_kids_ages,
            ('light tops, t-shirts', 'легкий верх, футболки'): baby_kids_ages,
            ('matching sets', 'комплекты'): baby_kids_ages,
            ('one-pieces, light', 'комбинезоны легкие'): baby_kids_ages,
            ('one-pieces, warm', 'комбинезоны утепленные'): baby_kids_ages,
            ('outerwear', 'верхняя одежда'): baby_kids_ages,
            ('sleepwear', 'для сна'): baby_kids_ages,
            ('skirts', 'юбки'): baby_kids_ages,
            ('swimwear', 'для плавания'): baby_kids_ages,
            ('underwear', 'нижнее белье'): baby_kids_ages,
            ('warm bottoms', 'теплый низ'): baby_kids_ages,
            ('warm tops', 'теплый верх'): baby_kids_ages,
            ('bulk lots', 'оптом'): baby_kids_ages,
            ('other', 'другое'): baby_kids_ages,
        },
        ('boys', 'мальчики'): {
            ('accessories', 'аксессуары'): baby_kids_ages,
            ('footwear', 'обувь'): baby_kids_ages,
            ('hats', 'головные уборы'): baby_kids_ages,
            ('light bottoms', 'легкий низ'): baby_kids_ages,
            ('light tops, t-shirts', 'легкий верх, футболки'): baby_kids_ages,
            ('matching sets', 'комплекты'): baby_kids_ages,
            ('one-pieces, light', 'комбинезоны легкие'): baby_kids_ages,
            ('one-pieces, warm', 'комбинезоны утепленные'): baby_kids_ages,
            ('outerwear', 'верхняя одежда'): baby_kids_ages,
            ('sleepwear', 'для сна'): baby_kids_ages,
            ('swimwear', 'для плавания'): baby_kids_ages,
            ('underwear', 'нижнее белье'): baby_kids_ages,
            ('warm bottoms', 'теплый низ'): baby_kids_ages,
            ('warm tops', 'теплый верх'): baby_kids_ages,
            ('bulk lots', 'оптом'): baby_kids_ages,
            ('other', 'другое'): baby_kids_ages,
        },
        ('unisex', 'унисекс'): {
            ('accessories', 'аксессуары'): baby_kids_ages,
            ('footwear', 'обувь'): baby_kids_ages,
            ('hats', 'головные уборы'): baby_kids_ages,
            ('light bottoms', 'легкий низ'): baby_kids_ages,
            ('light tops, t-shirts', 'легкий верх, футболки'): baby_kids_ages,
            ('matching sets', 'комплекты'): baby_kids_ages,
            ('one-pieces, light', 'комбинезоны легкие'): baby_kids_ages,
            ('one-pieces, warm', 'комбинезоны утепленные'): baby_kids_ages,
            ('outerwear', 'верхняя одежда'): baby_kids_ages,
            ('sleepwear', 'для сна'): baby_kids_ages,
            ('swimwear', 'для плавания'): baby_kids_ages,
            ('underwear', 'нижнее белье'): baby_kids_ages,
            ('warm bottoms', 'теплый низ'): baby_kids_ages,
            ('warm tops', 'теплый верх'): baby_kids_ages,
            ('bulk lots', 'оптом'): baby_kids_ages,
            ('other', 'другое'): baby_kids_ages,
        },
    },
    ('diapers, nappies, changing', 'подгузники, уход'): {
        ('changing tables', 'пеленальный стол'): {},
        ('changing  mats', 'пеленальная подстилка'): {},
        ('wipes', 'салфетки'): {},
        ('cloth diapers', 'подгузники матерчатые'): {},
        ('diaper bags', 'сумки для подгузников'): {},
        ('disposable diapers', 'подгузники одноразовые'): {},
        ('swim diapers', 'подгузники для плавания'): {},
        ('other', 'другое'): {},
    },
    ('feeding', 'кормление'): {
        ('bibs', 'нагрудник'): {},
        ('breast pads, shields', 'подкладки, накрытия'): {},
        ('breast pumps', 'молокоотсосы'): {},
        ('cups, bottles', 'чашки, бутылочки'): {},
        ('feeding pillows', 'подушка для кормления'): {},
        ('high chairs', 'стул для кормления'): {},
        ('plates, bowls', 'тарелки'): {},
        ('pacifiers', 'соски'): {},
        ('sterilisers, food warmers', 'стерилизаторы, подогреватели'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('prams, strollers, carriers', 'коляски, рюкзаки, переноски'): {
        ('twin or double strollers', 'двойная коляска'): {},
        ('three wheel strollers', 'трехколесная коляска'): {},
        ('four wheel strollers', 'четырехколесная коляска'): {},
        ('prams', 'классическая коляска'): {},
        ('carriers', 'переноски'): {},
        ('backpacks', 'frontpacks', 'рюкзаки'): {},
        ('slings', 'слинги'): {},
        ('other', 'другое'): {},
    },
    ('baby room, furniture', 'детская комната, мебель'): {
        ('mats, rugs', 'коврики, подстилки'): {},
        ('wall decor', 'настенные декорации'): {},
        ('wall letters', 'настенные буквы'): {},
        ('shelves', 'полки'): {},
        ('lamps, lighting', 'лампы, светильники'): {},
        ('tables, chairs', 'столы, стулья'): {},
        ('nursery furniture sets', 'наборы мебели'): {},
        ('rockers', 'кресла качалки'): {},
        ('other', 'другое'): {},
    },
    ('safety', 'безопасность'): {
        ('monitors', 'мониторы'): {},
        ('thermometers', 'термометры'): {},
        ('finger pinch guards', 'защита пальцев'): {},
        ('locks, latches', 'замки, запоры'): {},
        ('bed rails', 'барьер для кроватей'): {},
        ('corner cushions', 'накладки на углы'): {},
        ('outlet covers', 'заглушки для розеток'): {},
        ('safety gates', 'барьеры безопасности'): {},
        ('sleep positioners', 'позиционер для сна'): {},
        ('safety harnesses', 'упряжка безопасности'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('toys, activities, fun', 'игрушки, игры'): {
        ('activity gyms', 'спортивнo игровые'): {},
        ('blocks, sorters', 'кубики, сортировки'): {},
        ('crib toys', 'в кроватку'): {},
        ('developmental toys', 'развивающие'): {},
        ('rattles', 'погремушки'): {},
        ('mobiles', 'мобиле'): {},
        ('teethers', 'зуборезки'): {},
        ('jumping exercisers', 'прыгунки'): {},
        ('swings, rockers', 'качели, качалки'): {},
        ('play pens, play yards', 'игровые манежи'): {},
        ('play shades, tents', 'игровые тенты, палатки'): {},
        ('walkers', 'ходунки'): {},
        ('cars, trucks, vehicles', 'машины'): {},
        ('dolls', 'куклы'): {},
        ('musical', 'музыкальные'): {},
        ('pull along', 'каталки'): {},
        ('ride on', 'для езды'): {},
        ('interactive', 'интерактивные'): {},
        ('soft toys', 'мягкие игрушки'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('other', 'другое'): {},
}}
