# -*- coding: utf-8 -*-
"""'Clothing, accessories' part of product categories dictionary.

Must hold subcategories of 'Clothing, accessories'
category in the form of python dictionary data type.

"""

kids_sizes = {
    ('86 cm', '86 см'): {},
    ('92 cm', '92 см'): {},
    ('98 cm', '98 см'): {},
    ('104 cm', '104 см'): {},
    ('110 cm', '110 см'): {},
    ('116 cm', '116 см'): {},
    ('122 cm', '122 см'): {},
    ('128 cm', '128 см'): {},
    ('134 cm', '134 см'): {},
    ('140 cm', '140 см'): {},
    ('146 cm', '146 см'): {},
    ('152 cm', '152 см'): {},
    ('164 plus cm', '164 плюс см'): {},
}
men_sizes = {
    ('multiple sizes', 'несколько размеров'): {},
    ('S', 'S'): {},
    ('M', 'M'): {},
    ('L', 'L'): {},
    ('XL', 'XL'): {},
    ('XXL', 'XXL'): {},
    ('XXXL plus', 'XXXL плюс'): {},
}
adult_shoe_size = {
    ('200 mm', '200 мм'): {},
    ('210 mm', '210 мм'): {},
    ('220 mm', '220 мм'): {},
    ('230 mm', '230 мм'): {},
    ('240 mm', '240 мм'): {},
    ('250 mm', '250 мм'): {},
    ('260 mm', '260 мм'): {},
    ('270 mm', '270 мм'): {},
    ('280 mm', '280 мм'): {},
    ('290 mm', '290 мм'): {},
    ('300 mm', '300 мм'): {},
    ('310 mm', '310 мм'): {},
    ('320 plus mm', '320 плюс мм'): {},
}
kids_shoe_size = {
    ('80 mm', '80 мм'): {},
    ('90 mm', '90 мм'): {},
    ('100 mm', '100 мм'): {},
    ('110 mm', '110 мм'): {},
    ('120 mm', '120 мм'): {},
    ('130 mm', '130 мм'): {},
    ('140 mm', '140 мм'): {},
    ('150 mm', '150 мм'): {},
    ('160 mm', '160 мм'): {},
    ('170 mm', '170 мм'): {},
    ('180 mm', '180 мм'): {},
    ('190 mm', '190 мм'): {},
    ('200 plus mm', '200 плюс мм'): {},
}
women_sizes = {
    ('multiple sizes', 'несколько размеров'): {},
    ('XS', 'XS'): {},
    ('S', 'S'): {},
    ('M', 'M'): {},
    ('L', 'L'): {},
    ('XL plus', 'XL плюс'): {},
}
clothing_accessories = {('clothing, accessories', 'одежда, аксессуары'): {
    ('boys', 'мальчики'): {
        ('accessories', 'аксессуары'): {
            ('bags, backpacks', 'сумки, рюкзаки'): {},
            ('belts', 'ремни'): {
                ('black', 'черные'): {},
                ('brown', 'коричневые'): {},
                ('white', 'белые'): {},
                ('other', 'другое'): {},
            },
            ('belt buckles', 'пряжки ремней'): {},
            ('gloves, mittens', 'перчатки, варежки'): {},
            ('handkerchiefs', 'платки носовые'): {},
            ('hats', 'головные уборы'): {},
            ('scarves', 'шарфы'): {},
            ('sunglasses', 'очки темные'): {},
            ('suspenders', 'подтяжки'): {},
            ('ties', 'галстуки'): {},
            ('wallets', 'бумажникии'): {},
            ('other', 'другое'): {},
        },
        ('coats', 'пальто'): kids_sizes,
        ('costumes', 'маскарад, образы'): kids_sizes,
        ('footwear', 'обувь'): kids_shoe_size,
        ('jerseys, hoodies', 'толстовки'): kids_sizes,
        ('jackets', 'куртки'): kids_sizes,
        ('jeans', 'джинсы'): kids_sizes,
        ('shirts', 'рубашки'): kids_sizes,
        ('shorts', 'шорты'): kids_sizes,
        ('sleepwear, robes', 'пижамы, халаты'): kids_sizes,
        ('sportswear', 'спортивная одежда'): {
            ('top', 'верх'): kids_sizes,
            ('bottom', 'низ'): kids_sizes,
            ('other', 'другое'): kids_sizes,
        },
        ('socks', 'носки'): kids_shoe_size,
        ('suits', 'костюмы'): kids_sizes,
        ('sweaters', 'свитеры'): kids_sizes,
        ('swimwear', 'купальные костюмы'): kids_sizes,
        ('t-shirts', 'футболки'): kids_sizes,
        ('trousers', 'брюки'): kids_sizes,
        ('underwear', 'нижнее белье'): kids_sizes,
        ('uniforms', 'форма'): kids_sizes,
        ('winter clothes', 'зимняя одежда'): kids_sizes,
        ('bulk lots', 'оптом'): kids_sizes,
        ('other', 'другое'): kids_sizes,
    },
    ('men', 'мужчины'): {
        ('accessories', 'аксессуары'): {
            ('bags', 'сумки'): {},
            ('belts', 'ремни'): {
                ('black', 'черные'): {},
                ('brown', 'коричневые'): {},
                ('white', 'белые'): {},
                ('other', 'другое'): {},
            },
            ('belt buckles', 'пряжки ремней'): {},
            ('cufflinks', 'запонки'): {},
            ('gloves, mittens', 'перчатки, варежки'): {},
            ('handkerchiefs', 'платки носовые'): {},
            ('hats', 'головные уборы'): {},
            ('scarves', 'шарфы'): {},
            ('sunglasses', 'очки темные'): {},
            ('suspenders', 'подтяжки'): {},
            ('ties', 'галстуки'): {},
            ('wallets', 'бумажникии'): {},
            ('other', 'другое'): {},
        },
        ('costumes', 'маскарад, образы'): men_sizes,
        ('footwear', 'обувь'): adult_shoe_size,
        ('jerseys, hoodies', 'толстовки'): men_sizes,
        ('sportswear', 'спортивная одежда'): {
            ('top', 'верх'): men_sizes,
            ('bottom', 'низ'): men_sizes,
            ('other', 'другое'): men_sizes,
        },
        ('winter clothes', 'зимняя одежда'): men_sizes,
        ('casual shirts', 'повседневные рубашки'): men_sizes,
        ('dress shirts', 'рубашки'): men_sizes,
        ('t-shirts', 'футболки'): men_sizes,
        ('coats', 'пальто'): men_sizes,
        ('jackets', 'куртки'): men_sizes,
        ('jeans', 'джинсы'): men_sizes,
        ('trousers', 'брюки'): men_sizes,
        ('shorts', 'шорты'): men_sizes,
        ('sleepwear, robes', 'пижамы, халаты'): men_sizes,
        ('socks', 'носки'): adult_shoe_size,
        ('suits', 'костюмы'): men_sizes,
        ('sweaters', 'свитеры'): men_sizes,
        ('swimwear', 'купальные костюмы'): men_sizes,
        ('underwear', 'нижнее белье'): men_sizes,
        ('bulk lots', 'оптом'): men_sizes,
        ('other', 'другое'): men_sizes,
    },
    ('girls', 'девочки'): {
        ('accessories', 'аксессуары'): {
            ('bags', 'сумки'): {},
            ('backpacks', 'рюкзаки'): {},
            ('belts', 'ремни'): {},
            ('gloves, mittens', 'перчатки, варежки'): {},
            ('hair accessories', 'аксессуары для волос'): {},
            ('handbags', 'женские сумки'): {},
            ('handkerchiefs', 'платки носовые'): {},
            ('hats', 'головные уборы'): {},
            ('purses, wallets', 'кошельки'): {},
            ('scarves', 'шарфы'): {},
            ('sunglasses', 'очки темные'): {},
            ('other', 'другое'): {},
        },
        ('coats', 'пальто'): kids_sizes,
        ('costumes', 'маскарад, образы'): kids_sizes,
        ('dresses', 'платья'): {
            ('casual', 'повседневные'): kids_sizes,
            ('evening', 'вечерние'): kids_sizes,
            ('other', 'другое'): kids_sizes,
        },
        ('footwear', 'обувь'): kids_shoe_size,
        ('hosiery, socks', 'чулочно-носочные'): {
            ('leg warmers', 'гетры'): {},
            ('tights', 'колготки'): {
                ('size 1', 'размер 1'): {},
                ('size 2', 'размер 2'): {},
                ('size 3', 'размер 3'): {},
                ('size 4', 'размер 4'): {},
            },
            ('socks', 'носки'): kids_shoe_size,
            ('stockings', 'гольфы'): kids_sizes,
            ('other', 'другое'): kids_sizes,
        },
        ('jerseys, hoodies', 'толстовки'): kids_sizes,
        ('jackets', 'куртки'): kids_sizes,
        ('jeans', 'джинсы'): kids_sizes,
        ('shirts', 'рубашки'): kids_sizes,
        ('shorts', 'шорты'): kids_sizes,
        ('skirts', 'юбки'): kids_sizes,
        ('sleepwear, robes', 'пижамы, халаты'): kids_sizes,
        ('sportswear', 'спортивная одежда'): {
            ('top', 'верх'): kids_sizes,
            ('bottom', 'низ'): kids_sizes,
            ('other', 'другое'): kids_sizes,
        },
        ('suits', 'костюмы'): kids_sizes,
        ('sweaters', 'свитеры'): kids_sizes,
        ('swimwear', 'купальные костюмы'): kids_sizes,
        ('t-shirts', 'футболки'): kids_sizes,
        ('tops, blouses', 'топы, блузы'): kids_sizes,
        ('trousers', 'брюки'): kids_sizes,
        ('underwear', 'нижнее белье'): kids_sizes,
        ('uniforms', 'форма'): kids_sizes,
        ('winter clothes', 'зимняя одежда'): kids_sizes,
        ('bulk lots', 'оптом'): kids_sizes,
        ('other', 'другое'): kids_sizes,
    },
    ('women', 'женщины'): {
        ('accessories', 'аксессуары'): {
            ('bags', 'сумки'): {},
            ('backpacks', 'рюкзаки'): {},
            ('belts', 'ремни'): {},
            ('gloves, mittens', 'перчатки, варежки'): {},
            ('hair accessories', 'аксессуары для волос'): {},
            ('handbags', 'женские сумки'): {},
            ('handkerchiefs', 'платки носовые'): {},
            ('hats', 'головные уборы'): {},
            ('purses, wallets', 'кошельки'): {},
            ('scarves', 'шарфы'): {},
            ('sunglasses', 'очки темные'): {},
            ('wigs, extensions', 'парики'): {},
            ('other', 'другое'): {},
        },
        ('coats', 'пальто'): women_sizes,
        ('costumes', 'маскарад, образы'): women_sizes,
        ('dresses', 'платья'): {
            ('casual', 'повседневные'): women_sizes,
            ('evening', 'вечерние'): women_sizes,
            ('other', 'другое'): women_sizes,
        },
        ('footwear', 'обувь'): adult_shoe_size,
        ('hosiery, socks', 'чулочно-носочные'): {
            ('leg warmers', 'гетры'): {},
            ('pantyhose, tights', 'колготки, чулки'): {
                ('size 1', 'размер 1'): {},
                ('size 2', 'размер 2'): {},
                ('size 3', 'размер 3'): {},
                ('size 4', 'размер 4'): {},
            },
            ('socks', 'носки'): adult_shoe_size,
            ('stockings, thigh-highs', 'чулки'): women_sizes,
            ('other', 'другое'): women_sizes,
        },
        ('jerseys, hoodies', 'толстовки'): women_sizes,
        ('jackets', 'куртки'): women_sizes,
        ('jeans', 'джинсы'): women_sizes,
        ('lingerie, underwear', 'нижнее белье'): {
            ('bras, bra sets', 'бюстгалтеры, комплекты'): {
                ('multiple sizes', 'несколько размеров'): {},
                ('one size items', 'один размер'): {},
            },
            ('panties', 'трусы'): women_sizes,
            ('adult', 'для взрослых'): women_sizes,
            ('other', 'другое'): women_sizes,
        },
        ('maternity', 'для беременных'): {
            ('dresses', 'платья'): women_sizes,
            ('bras, bra sets', 'бюстгалтеры, комплекты'): {
                ('multiple sizes', 'несколько размеров'): {},
                ('one size items', 'один размер'): {},
            },
            ('jeans', 'джинсы'): women_sizes,
            ('trousers', 'брюки'): women_sizes,
            ('sleepwear, underwear', 'пижамы, белье'): women_sizes,
            ('shorts', 'шорты'): women_sizes,
            ('skirts', 'юбки'): women_sizes,
            ('sweaters', 'свитеры'): women_sizes,
            ('swimwear', 'купальные костюмы'): women_sizes,
            ('t-shirts', 'футболки'): women_sizes,
            ('tops, blouses', 'топы, блузы'): women_sizes,
            ('bulk lots', 'оптом'): women_sizes,
            ('other', 'другое'): women_sizes,
        },
        ('shirts', 'рубашки'): women_sizes,
        ('shorts', 'шорты'): women_sizes,
        ('skirts', 'юбки'): women_sizes,
        ('sleepwear, robes', 'пижамы, халаты'): women_sizes,
        ('sportswear', 'спортивная одежда'): {
            ('top', 'верх'): women_sizes,
            ('bottom', 'низ'): women_sizes,
            ('other', 'другое'): women_sizes,
        },
        ('suits', 'костюмы'): women_sizes,
        ('sweaters', 'свитеры'): women_sizes,
        ('swimwear', 'купальные костюмы'): women_sizes,
        ('t-shirts', 'футболки'): women_sizes,
        ('tops, blouses', 'топы, блузы'): women_sizes,
        ('trousers', 'брюки'): women_sizes,
        ('winter clothes', 'зимняя одежда'): women_sizes,
        ('bulk lots', 'оптом'): women_sizes,
        ('other', 'другое'): women_sizes,
    },
}}
