# -*- coding: utf-8 -*-
"""'craft' part of product categories dictionary.

Must hold subcategories of 'craft'
category in the form of python dictionary data type.

"""
craft = {('craft', 'рукоделие, ремесло'): {
    # add 'in bulk' or 'whole sale'
    # add 'other'
    ('baking', 'выпекание'): {},
    ('crochet', 'вязание крючком'): {
        ('completed works', 'законченные работы'): {},
        ('hooks', 'крючки'): {},
        ('kits', 'наборы'): {},
        ('thread', 'нитки'): {},
        ('other', 'другое'): {},
    },
    ('cross-stitch', 'вышивка крестиком'): {
        ('charts', 'диаграммы'): {},
        ('completed works', 'законченные работы'): {},
        ('cottons', 'нитки'): {},
        ('fabric', 'ткань'): {},
        ('kits', 'наборы'): {},
        ('patterns', 'шаблоны, схемы'): {},
        ('other', 'другое'): {},
    },
    ('embroidery', 'вышивка'): {
        ('completed works', 'законченные работы'): {},
        ('cottons', 'нитки'): {},
        ('patterns', 'шаблоны, схемы'): {},
        ('other', 'другое'): {},
    },
    ('fabric', 'ткань'): {
        ('corduroy', 'вельвет'): {},
        ('cotton', 'хлопок'): {},
        ('flannel', 'фланнель'): {},
        ('lace', 'кружева'): {},
        ('linen', 'полотно'): {},
        ('lycra', 'лайкра'): {},
        ('satin', 'сатин'): {},
        ('silk', 'шелк'): {},
        ('synthetics', 'синтетика'): {},
        ('blends', 'смешанные'): {},
        ('upholstery, drapery', 'драпировка'): {},
        ('velvet, velour', 'вельвет, велюр'): {},
        ('wool', 'шерсть'): {},
        ('other', 'другое'): {},
    },
    ('jewelery, beads', 'бисер, ювелирное'): {
        ('completed works', 'законченные работы'): {},
        ('beads', 'бисер'): {},
        ('charms', 'медальоны'): {},
        ('cord, thread, wire', 'шнуры, струны'): {},
        ('jewelry findings', 'фурнитура'): {
            ('bead caps', 'колпачки'): {},
            ('chains', 'цепочки'): {},
            ('clasps, hooks', 'крючки, застежки'): {},
            ('crimp', 'завитки'): {},
            ('connectors', 'соединения'): {},
            ('earring findings', 'серьги'): {},
            ('rings', 'кольца'): {},
            ('pins, needles', 'булавки'): {},
            ('spacer beads', 'бусины'): {},
            ('other', 'другое'): {},
        },
        ('kits', 'наборы'): {},
        ('tools', 'инструмент'): {},
        ('other', 'другое'): {},
    },
    ('kids craft', 'детское рукоделие'): {},
    ('knitting, weaving', 'вязание, ткачество'): {
        ('kits', 'наборы'): {},
        ('needles', 'спицы'): {},
        ('machine knitting', 'машинная вязка'): {},
        ('patterns', 'шаблоны, схемы'): {
            ('adult clothing', 'одежда взрослая'): {},
            ('afghans', 'шали, накидки'): {},
            ('baby, children', 'одежда детская'): {},
            ('doll clothing', 'одежда для кукол'): {},
            ('dolls, toys', 'куклы, игрушки'): {},
            ('home decor', 'декоративное'): {},
            ('purses, wallets', 'кошельки'): {},
            ('other', 'другое'): {},
        },
        ('looms, frames', 'ткацкие станки'): {},
        ('weaving accessories', 'ткацкие аксессуары'): {},
        ('wool', 'шерсть, пряжа'): {},
        ('other', 'другое'): {},
    },
    ('mosaic', 'мозаика'): {
        ('completed works', 'законченные работы'): {},
        ('gems', 'камни'): {},
        ('kits', 'наборы'): {},
        ('tiles', 'плитка'): {},
        ('tools', 'инструмент'): {},
        ('other', 'другое'): {},
    },
    ('pottery, ceramics', 'керамика, гончарное'): {
        ('completed works', 'законченные работы'): {},
        ('molds', 'формы'): {},
        ('kits', 'наборы'): {},
        ('clays, glazes, paints', 'глина, глазурь, краска'): {},
        ('plaster', 'гипс'): {},
        ('polymer clay', 'глина полимерная'): {},
        ('kilns', 'печи'): {},
        ('tools', 'инструмент'): {},
        ('pottery wheels', 'гончарные круги'): {},
        ('ready-to-paint pottery', 'изделия для окраски'): {},
        ('other', 'другое'): {},
    },
    ('quilting', 'лоскутные одеяла'): {
        ('completed works', 'законченные работы'): {},
        ('batting', 'ватин'): {},
        ('blocks', 'лоскутки'): {},
        ('patterns', 'шаблоны, схемы'): {},
        ('tops', 'верх'): {},
        ('kits', 'наборы'): {},
        ('tools, equipment', 'инструмент, оборудование'): {},
        ('other', 'другое'): {},
    },
    ('scrapbooking', 'скрапбукинг'): {
        ('adhesive, glue', 'клей'): {},
        ('card, paper', 'картон, бумага'): {},
        ('embellishment', 'украшения'): {},
        ('kits', 'наборы'): {},
        ('organisers, albums', 'альбомы, органайзеры'): {},
        ('stickers', 'стикеры'): {},
        ('tools', 'инструмент'): {},
        ('other', 'другое'): {},
    },
    ('sewing', 'шитье'): {
        ('patterns', 'шаблоны, схемы'): {
            ('baby, kids', 'дети, младенцы'): {},
            ('costumes', 'маскарад, образы'): {},
            ('pets', 'домашние животные'): {},
            ('dolls', 'куклы, игрушки'): {},
            ('men', 'мужчины'): {},
            ('women', 'женщины'): {},
            ('other', 'другое'): {},
        },
        ('buttons', 'пуговицы, кнопки'): {},
        ('embellishment', 'украшения'): {},
        ('sewing machines, accessories', 'швейные машины, аксессуары'): {
            ('sewing machines', 'швейные машины'): {},
            ('accessories', 'аксессуары'): {
                ('bobbins, cases', 'бабины, челноки'): {},
                ('feet', 'ножки'): {},
                ('needles', 'иглы'): {},
                ('other', 'другое'): {},
            },
        },
        ('thread', 'нитки'): {},
        ('toy making', 'делаем игрушки'): {},
        ('zips', 'молнии'): {},
        ('other', 'другое'): {},
    },
    ('stamping, embossing', 'тиснение, штамповка'): {
        ('completed works', 'законченные работы'): {},
        ('embossing powders', 'порошок для тиснения'): {},
        ('embossing stencils', 'трафареты'): {},
        ('ink, pads', 'чернила, подушки'): {},
        ('kits', 'наборы'): {},
        ('paper, envelopes', 'бумага, конверты'): {},
        ('stamps', 'штампы'): {
            ('abstract', 'абстракция'): {},
            ('alphabet, numbers', 'алфавит, цифры'): {},
            ('animals', 'животные'): {},
            ('borders, backgrounds', 'края, фон'): {},
            ('characters', 'персонажи'): {},
            ('floral', 'цветы'): {},
            ('holidays, occasions', 'праздники'): {},
            ('love, weddings', 'любовь, свадьба'): {},
            ('poems, phrases', 'стихи, фразы'): {},
            ('people', 'люди'): {},
            ('religious', 'религиозный мотив'): {},
            ('sports', 'спорт'): {},
            ('toys', 'игрушки'): {},
            ('other', 'другое'): {},
        },
        ('tools, equipment', 'инструмент, оборудование'): {},
        ('other', 'другое'): {},
    },
    ('woodcraft', 'дерево'): {
        ('completed works', 'законченные работы'): {},
        ('kits', 'наборы'): {},
        ('lumber', 'лесоматериал'): {},
        ('woodcarving', 'резка по дереву'): {
            ('wood', 'дерево'): {},
            ('kits', 'наборы'): {},
            ('tools', 'инструмент'): {},
            ('other', 'другое'): {},
        },
        ('woodturning', 'токарное дело'): {
            ('wood', 'дерево'): {},
            ('tools', 'инструмент'): {},
            ('other', 'другое'): {},
        },
        ('supplies', 'расходные'): {},
        ('tools', 'инструмент'): {},
        ('other', 'другое'): {},
    },
    ('candle making', 'изготовление свечей'): {
        ('completed works', 'законченные работы'): {},
        ('bags, packaging', 'упаковка'): {},
        ('kits', 'наборы'): {},
        ('molds', 'формы'): {},
        ('wax', 'воск'): {},
        ('wicks', 'фитиль'): {},
        ('dyes', 'краситель'): {},
        ('embeds', 'вставки'): {},
        ('jars, holders', 'подставки, сосуды'): {},
        ('powders', 'порошки'): {},
        ('scents, fragrances', 'ароматы'): {},
        ('tools', 'инструмент'): {},
        ('warming pots', 'разогреватели'): {},
        ('other', 'другое'): {},
    },
    ('other', 'другое'): {},
}
}
