# -*- coding: utf-8 -*-
"""'Home, garden' part of product categories dictionary.

Must hold subcategories of 'Home, garden'
category in the form of python dictionary data type.

"""

home_garden = {('home, garden', 'дом, дача'): {
    #('bathroom',),
    #('bedroom',),
    #('cleaning',): {
    #('heating, cooling, air',),
    #('home decor',),
    #('home security, locks',),
    #('kitchen',),
    #('lamps, lighting',),
    #('laundry',),
    #('lounge, dining, hall',),
    #('outdoor, garden',),
    #('rugs, carpets',),
    #('window treatment',)]
    ('bathroom', 'ванная, туалет'): {
        ('accessories', 'аксессуары'): {},
        ('mats, rugs', 'коврики'): {},
        ('baskets, bins', 'корзины, контейнеры'): {},
        ('cabinets', 'шкафы'): {},
        ('kids', 'детское'): {},
        ('mirrors', 'зеркала'): {},
        ('non-slip mats', 'нескользящие коврики'): {},
        ('scales', 'весы'): {},
        ('shelves', 'полки'): {},
        ('shower curtains', 'занавески для душа'): {},
        ('showerheads', 'лейки'): {},
        ('soap dishes, dispensers', 'мыльницы, диспенсеры'): {},
        ('toilet brushes, holders', 'туалетные щетки'): {},
        ('toilet seats', 'туалетные сидения'): {},
        ('toilet tissue holders', 'для туалетной бумаги'): {},
        ('toothbrush holders', 'для зубных щеток'): {},
        ('towels', 'полотенца'): {},
        ('towel rails', 'вешалки для полотенец'): {},
        ('vanities', 'ванные гарнитуры'): {},
        ('hooks, hangers', 'крючки, вешалки'): {},
        ('other', 'другое'): {},
    },
    ('bedroom', 'спальня'): {
        ('furniture', 'мебель'): {
            ('wardrobes', 'шкафы'): {},
            ('beds', 'кровати'): {
                ('single', 'сингл'): {},
                ('double', 'дабл'): {},
                ('queen', 'квин'): {},
                ('king', 'кинг'): {},
                ('kids beds, bunks', 'детские'): {},
                ('other', 'другое'): {},
            },
            ('bed frames', 'основание кровати'): {
                ('single', 'сингл'): {},
                ('double', 'дабл'): {},
                ('queen', 'квин'): {},
                ('king', 'кинг'): {},
                ('other', 'другое'): {},
            },
            ('bedroom sets', 'спальные гарнитуры'): {},
            ('dressers', 'туалетные столики'): {},
            ('headboards', 'спинка кровати'): {},
            ('mattresses', 'матрасы'): {
                ('single', 'сингл'): {},
                ('double', 'дабл'): {},
                ('queen', 'квин'): {},
                ('king', 'кинг'): {},
                ('other', 'другое'): {},
            },
            ('nightstands', 'ночные столики'): {},
            ('drawers', 'комоды'): {},
            ('chests, trunks', 'сундуки'): {},
            ('other', 'другое'): {},
        },
        ('bedding', 'постельные принадлежности'): {
            ('single', 'сингл'): {
                ('bedspreads', 'покрывала'): {},
                ('blankets', 'одеяла'): {},
                ('comforters, duvets', 'стеганные одеяла'): {},
                ('duvet covers, sets', 'пододеяльники'): {},
                ('mattress protector', 'защита матраса'): {},
                ('quilts', 'лоскутные одеяла'): {},
                ('sets', 'комплекты'): {},
                ('sheets', 'простыни'): {},
                ('other', 'другое'): {},
            },
            ('double', 'дабл'): {
                ('bedspreads', 'покрывала'): {},
                ('blankets', 'одеяла'): {},
                ('comforters, duvets', 'стеганные одеяла'): {},
                ('duvet covers, sets', 'пододеяльники'): {},
                ('mattress protector', 'защита матраса'): {},
                ('quilts', 'лоскутные одеяла'): {},
                ('sets', 'комплекты'): {},
                ('sheets', 'простыни'): {},
                ('other', 'другое'): {},
            },
            ('queen', 'квин'): {
                ('bedspreads', 'покрывала'): {},
                ('blankets', 'одеяла'): {},
                ('comforters, duvets', 'стеганные одеяла'): {},
                ('duvet covers, sets', 'пододеяльники'): {},
                ('mattress protector', 'защита матраса'): {},
                ('quilts', 'лоскутные одеяла'): {},
                ('sets', 'комплекты'): {},
                ('sheets', 'простыни'): {},
                ('other', 'другое'): {},
            },
            ('king', 'кинг'): {
                ('bedspreads', 'покрывала'): {},
                ('blankets', 'одеяла'): {},
                ('comforters, duvets', 'стеганные одеяла'): {},
                ('duvet covers, sets', 'пододеяльники'): {},
                ('mattress protector', 'защита матраса'): {},
                ('quilts', 'лоскутные одеяла'): {},
                ('sets', 'комплекты'): {},
                ('sheets', 'простыни'): {},
                ('other', 'другое'): {},
            },
            ('kids bedding', 'детская постель'): {},
            ('cushions', 'декоративные подушки'): {},
            ('pillow shams', 'декоративные наволочки'): {},
            ('pillows', 'подушки'): {},
            ('pillowcases', 'наволочки'): {},
            ('other', 'другое'): {},
        },
        ('towels', 'полотенца'): {},
        ('other', 'другое'): {},
    },
    ('cleaning', 'уборка'): {
        ('bins', 'контейнеры'): {},
        ('brooms, mops', 'швабры, метлы'): {},
        ('cleaning supplies', 'расходные'): {},
        ('steam mops', 'паровые швабры'): {},
        ('vacuum cleaners', 'пылесосы'): {},
        ('other', 'другое'): {},
        #bag vacuums
        #bagless Vacuums
        #Wet/Dry Vacuums
        #Handheld Vacuums
        #Bags,  accessories
        #industrial vacuums
        #other vacuums
    },
    ('heating, cooling, air', 'обогрев, охлаждение, воздух'): {
        ('air conditioning', 'кондиционеры'): {},
        ('air filters', 'фильтры воздуха'): {},
        ('air purifiers', 'очистители воздуха'): {},
        ('dehumidifiers', 'осушители воздуха'): {},
        ('heating systems', 'отопительные системы'): {},
        ('humidifiers', 'увлажнители воздуха'): {},
        ('fans', 'вентиляторы'): {},
        ('fireplaces, stoves', 'камины, печи'): {},
        ('heaters', 'обогреватели'): {},
        ('water heaters', 'обогреватели воды'): {},
        ('other', 'другое'): {},
    },
    ('home decor', 'украшение дома'): {
        ('afghans, throws', 'накидки'): {},
        ('baskets', 'корзины'): {},
        ('bottles, jars', 'сосуды'): {},
        ('boxes, tins', 'коробки, банки'): {},
        ('candle holders', 'подсвечники'): {},
        ('candles', 'свечи'): {},
        ('clocks', 'часы'): {},
        ('cushions', 'декоративные подушки'): {},
        ('door accessories', 'украшение дверей'): {},
        ('floral decor', 'цветы'): {},
        ('frames', 'рамы, рамки'): {},
        ('home fragrances', 'ароматы'): {},
        ('indoor fountains', 'фонтаны'): {},
        ('mirrors', 'зеркала'): {},
        ('ornaments, sculptures', 'орнамент, скульптура'): {},
        ('plaques, signs', 'таблички, знаки'): {},
        ('plates, bowls', 'тарелки'): {},
        ('posters', 'плакаты'): {},
        ('racks, stands', 'вешалки, стойки'): {},
        ('room dividers', 'разделители комнат'): {},
        ('vases', 'вазы'): {},
        ('crystal', 'хрусталь'): {},
        ('wall decor', 'настенный декор'): {},
        ('other', 'другое'): {},
    },
    ('home security, locks', 'безопасность, замки'): {
        ('locks', 'замки'): {},
        ('safes', 'сейфы'): {},
        ('security cameras', 'камеры безопасности'): {},
        ('security systems', 'системы безопасности'): {},
        ('sensors, motion detectors', 'сенсоры, детекторы'): {},
        ('smoke, gas detectors', 'детекторы газа, дыма'): {},
        ('other', 'другое'): {},
    },
    ('kitchen', 'кухня'): {
        #('bar tools, accessories',): {
        #('cookware',): {
        #('furniture',): {
        #('knives, boards',): {
        #('linens',): {
        #('major appliances',): {
        #    #('cooktops, ovens',): {
        #    #('microwaves',): {},
        #    #('dishwashers',): {},
        #    #('fridge, freezer',): {
        #('small appliances',): {
        #('storage, containers',): {
        #('tableware',): {
        #    #('cutlery',): {},
        #    #('cups, glasses',): {
        #    #('dinnerware, serving pieces',): {
        #('tea, coffee making',): {
        #('tools, accessories',): {
        ('bar tools, accessories', 'барные аксессуары'): {
            ('bottle stoppers', 'пробки'): {},
            ('coasters', 'подставки'): {},
            ('cocktail shakers', 'шейкеры'): {},
            ('sets', 'наборы'): {},
            ('corkscrews, openers', 'штопоры'): {},
            ('decanters', 'графины'): {},
            ('flasks', 'фляжки'): {},
            ('home bars', 'домашние бары'): {},
            ('ice buckets', 'ведерки для льда'): {},
            ('wine coolers', 'кулеры для вина'): {},
            ('wine bags, carriers', 'сумки для вина'): {},
            ('wine racks', 'винные стеллажи'): {},
            ('other', 'другое'): {},
        },
        ('cookware', 'кухонная посуда'): {
            ('bakeware', 'выпекание'): {
                ('baking dishes', 'блюда'): {},
                ('baking tins, trays', 'лотки, подносы'): {},
                ('pots', 'горшки'): {},
                ('sets', 'наборы'): {},
                ('other', 'другое'): {},
            },
            ('casseroles', 'запекания'): {},
            ('sets', 'наборы'): {},
            ('microwave cookware', 'микроволновкa'): {},
            ('frying pans', 'сковороды'): {},
            ('roasters', 'жаровни'): {},
            ('saucepans', 'кастрюли'): {},
            ('steamers', 'пароварки'): {},
            ('pots', 'горшки'): {},
            ('woks', 'воки'): {},
            ('other', 'другое'): {},
        },
        ('furniture', 'мебель'): {
            ('stools', 'табуреты'): {},
            ('bar stools', 'барные стулья'): {},
            ('cabinets', 'шкафы'): {},
            ('cupboards', 'буфеты'): {},
            ('dinning sets', 'комплекты мебели'): {},
            ('tables', 'столы'): {},
            ('chairs', 'кресла, стулья'): {},
            ('other', 'другое'): {},
        },
        ('knives, boards', 'ножи, доски'): {
            ('single knives', 'единичные ножи'): {},
            ('sharpeners', 'точилки'): {},
            ('sets', 'наборы'): {},
            ('other', 'другое'): {},
        },
        ('kitchen linens', 'столовое, кухонное белье'): {
            ('aprons', 'фартуки'): {},
            ('napkins', 'салфетки'): {},
            ('oven mitts', 'варежки'): {},
            ('placemats', 'плейсмат'): {},
            ('potholders', 'прихватки'): {},
            ('tablecloths', 'скатерти'): {},
            ('towels', 'полотенца'): {},
            ('dishcloths', 'для мытья посуды'): {},
            ('sets', 'наборы'): {},
            ('other', 'другое'): {},
        },
        ('major appliances', 'крупные бытовые приборы'): {
            ('cooktops, ovens', 'кухонные плиты'): {
                ('electric', 'электро'): {},
                ('gas', 'газовые'): {},
                ('hoods', 'вытяжки'): {},
                ('other', 'другое'): {},
            },
            ('dishwashers', 'посудомоечные машины'): {},
            ('fridges, freezers', 'холодильники, морозильники'): {
                ('freezers', 'морозильники'): {},
                ('fridge-freezers', 'холодильник-морозильники'): {},
                ('fridges', 'холодильники'): {},
                ('other', 'другое'): {},
            },
            ('microwaves', 'микроволновки'): {},
            ('water coolers', 'кулеры для воды'): {},
            ('other', 'другое'): {},
        },
        ('small appliances', 'мелкие бытовые приборы'): {
            ('blenders', 'блендеры'): {},
            ('can openers', 'консервные ножи'): {},
            ('cookers, steamers', 'пароварки, самоварки'): {},
            ('food processors', 'кухонные комбайны'): {},
            ('ice cream makers', 'готовим мороженное'): {},
            ('grills, fryers', 'грили, фритюрницы'): {},
            ('juicers', 'соковыжималки'): {},
            ('kettles, jugs', 'электрочайники'): {},
            ('meat grinders', 'мясорубки'): {},
            ('mixers', 'миксеры'): {},
            ('sandwich makers', 'сандвич мейкеры'): {},
            ('scales', 'весы'): {},
            ('slicers, electric knives', 'слайсеры, электроножи'): {},
            ('toasters', 'тостеры'): {},
            ('waffle makers', 'готовим вафли'): {},
            ('water filters', 'фильтры для воды'): {},
            ('other', 'другое'): {},
        },
        ('storage, containers', 'хранение, контейнеры'): {
            ('canisters', 'банки'): {},
            ('containers', 'контейнеры'): {},
            ('racks, holders', 'стеллажи'): {},
            ('spice jars, racks', 'для приправ'): {},
            ('vacuum sealers', 'вакуумная упаковка'): {},
            ('other', 'другое'): {},
        },
        ('tableware', 'посуда, приборы'): {
            ('cups, glasses', 'стаканы, чашки'): {
                ('cups, saucers', 'чашки, блюдца'): {},
                ('mugs', 'кружки'): {},
                ('tumblers', 'высокие стаканы'): {},
                ('wine glasses', 'бокалы'): {},
                ('martini glasses', 'для мартини'): {},
                ('other', 'другое'): {},
            },
            ('cutlery', 'столовые приборы'): {},
            ('dinnerware, serving pieces', 'посуда'): {
                ('bowls', 'глубокие тарелки'): {},
                ('pitchers', 'кувшины'): {},
                ('plates', 'тарелки'): {},
                ('platters', 'блюда'): {},
                ('salad bowls', 'салатные тарелки'): {},
                ('salt, pepper shakers', 'соль, перец'): {},
                ('sets', 'наборы'): {},
                ('trays', 'подносы'): {},
                ('other', 'другое'): {},
            },
        },
        ('tea, coffee making', 'чай, кофе'): {
            ('coffee grinders', 'кофемолки'): {},
            ('coffee machines', 'кофеварки'): {},
            ('coffee plungers', 'плунжеры'): {},
            ('milk jugs, sugar bowls', 'молоко, сахар'): {},
            ('teapots', 'заварочные чайники'): {},
            ('tea sets', 'чайные наборы'): {},
            ('other', 'другое'): {},
        },
        ('tools, accessories', 'инструмент, аксессуары'): {
            ('cake decorating', 'декорация тортов'): {},
            ('can openers', 'консервные ножи'): {},
            ('colanders, strainers', 'дуршлаги'): {},
            ('cookie cutters', 'формы для печений'): {},
            ('thermometers', 'термометры'): {},
            ('graters', 'терки'): {},
            ('molds', 'формы'): {},
            ('measuring', 'для измерения'): {},
            ('mixing, sifting', 'просев, смешивание'): {},
            ('peelers', 'пилеры'): {},
            ('refrigerator magnets', 'магниты'): {},
            ('salt, pepper mills', 'мельницы'): {},
            ('scissors, shears', 'ножницы'): {},
            ('scoops', 'ковши, черпаки'): {},
            ('shakers', 'шейкеры'): {},
            ('timers', 'таймеры'): {},
            ('trivets', 'подставки'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('lamps, lighting', 'лампы, светильники'): {
        ('chandeliers', 'люстры'): {},
        ('lamps', 'лампы'): {
            ('desk lamps', 'письменные лампы'): {},
            ('night lights', 'ночники'): {},
            ('floor lamps', 'напольные лампы'): {},
            ('table lamps', 'настольные лампы'): {},
            ('other', 'другое'): {},
        },
        ('light bulbs', 'лампочки'): {},
        ('bathroom lighting', 'освещение ванных'): {},
        ('pendant lighting', 'подвесное освещение'): {},
        ('recessed lighting', 'врезное освещение'): {},
        ('wall lamps', 'настенные лампы'): {},
        ('other', 'другое'): {},
    },
    ('laundry', 'стирка'): {
        ('supplies', 'расходные'): {
            ('bleaches, stain removers', 'отбеливатели'): {},
            ('detergents', 'моющие средства'): {},
            ('fabric softeners', 'кондиционеры'): {},
            ('pegs', 'прищепки'): {},
            ('other', 'другое'): {},
        },
        ('clotheslines, racks', 'сушки для белья'): {},
        ('dryers', 'сушилки'): {},
        ('fittings, parts', 'фитинги, запчасти'): {},
        ('irons', 'утюги'): {},
        ('ironing boards', 'гладильные доски'): {},
        ('hampers, bins, bags', 'корзины'): {},
        ('tubs', 'мойки'): {},
        ('washing machines', 'стиральные машины'): {
            ('front loader', 'вертикальная загрузка'): {},
            ('top loader', 'загрузка сверху'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('lounge, dining, hall', 'холл, гостинная, столовая'): {
        ('beanbags', 'кресло мешки'): {},
        ('cabinets', 'шкафы'): {
            ('buffets', 'буфеты'): {},
            ('wall units', 'стенки'): {},
            ('display units', 'стойки'): {},
            ('other', 'другое'): {},
        },
        ('bookshelves, bookcases', 'книжные полки, шкафы'): {},
        ('chairs', 'кресла, стулья'): {
            ('armchairs', 'кресла'): {},
            ('dining chairs', 'обеденные стулья'): {},
            ('recliners', 'реклайнеры'): {},
            ('rocking chairs', 'кресло-качалки'): {},
            ('other', 'другое'): {},
        },
        ('desks', 'столы'): {},
        ('dining suites', 'обеденные столы, стулья'): {
            ('4 seater', 'на 4 человека'): {},
            ('6 seater', 'на 6 человек'): {},
            ('other', 'другое'): {},
        },
        ('entertainment units', 'развлекательные центры'): {},
        ('lounge suites', 'мягкая мебель'): {
            ('2 seater couches', '2 местные диваны'): {},
            ('3 seater couches', '3 местные диваны'): {},
            ('armchairs', 'кресла'): {},
            ('sofa beds', 'диван-кровати'): {},
            ('futons', 'футоны'): {},
            ('suites', 'комплекты'): {},
            ('other', 'другое'): {},
        },
        ('ottomans, footstools', 'кушетки'): {},
        ('tables', 'столы'): {
            ('coffee tables', 'кофейные столики'): {},
            ('dining tables', 'обеденные столы'): {},
            ('hall tables', 'столы для прихожих'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('outdoor, garden', 'дачная, уличная мебель'): {
        #('BBQs',),
        #('flowers, trees, plants',),
        #('garden decor',),
        #('garden power tools',),
        #('garden structures, fencing',),
        #('gardening supplies',),
        #('lawnmowers',),
        #('outdoor cooking, eating',),
        #('outdoor furniture',),
        #('outdoor lighting',),
        #('pools, spas, saunas',)
        ('BBQs', 'барбекью'): {},
        ('flowers, trees, plants', 'цветы, растения, деревья'): {
            ('aquatic', 'водные'): {},
            ('bonsai', 'бонзай'): {},
            ('cactus, succulents', 'кактусы, суккуленты'): {},
            ('flowers', 'цветы'): {
                ('bulbs, roots', 'корни, луковицы'): {},
                ('flower plants, seedlings', 'крупномерные, саженцы'): {},
                ('flower seeds', 'семена'): {},
                ('perennials', 'многолетние'): {},
                ('other', 'другое'): {},
            },
            ('grasses, flax', 'газонная трава'): {},
            ('herbs', 'травы'): {},
            ('houseplants', 'комнатные растения'): {},
            ('palms, ferns', 'пальмы'): {},
            ('roses', 'розы'): {},
            ('shrubs', 'кусты'): {},
            ('trees', 'деревья'): {},
            ('tropicals', 'тропические'): {
                ('plants', 'крупномерные'): {},
                ('seedlings', 'саженцы'): {},
                ('seeds', 'семена'): {},
                ('other', 'другое'): {},
            },
            ('vegetables, fruits', 'овощные, фруктовые'): {
                ('plants', 'крупномерные'): {},
                ('seedlings', 'саженцы'): {},
                ('seeds, bulbs', 'семена, луковицы'): {},
                ('other', 'другое'): {},
            },
            ('vines, groundcover', 'лианы, покрывные'): {},
            ('other', 'другое'): {},
        },
        ('garden decor', 'дачный, садовый декор'): {
            ('flags', 'флаги'): {},
            ('flag poles, parts', 'шесты для флагов'): {},
            ('plaques, signs', 'таблички, знаки'): {},
            ('garden sculpture', 'садовая скульптура'): {},
            ('outdoor ornaments', 'наружний орнамент'): {},
            ('stepping stones', 'камни ступеньки'): {},
            ('thermometers', 'термометры'): {},
            ('water features', 'водные'): {
                ('indoor fountains', 'фонтаны'): {},
                ('ponds', 'пруды'): {},
                ('other', 'другое'): {},
            },
            ('weathervanes', 'флюгеры'): {},
            ('wind chimes', 'колокольчики'): {},
            ('windmills', 'мельницы'): {},
            ('windwheels, windsocks', 'колеса, виндсок'): {},
            ('other', 'другое'): {},
        },
        ('garden power tools', 'оборудование, инструмент'): {
            ('leaf blowers,  vacuums', 'пылесосы, воздуходувы'): {},
            ('mulchers, chippers', 'измельчители'): {},
            ('pressure washers', 'мойки'): {},
            ('trimmers, cutters', 'кусторезы'): {},
            ('string trimmers', 'триммеры'): {},
            ('snow tools', 'уборка снега'): {},
            ('tillers', 'культиваторы'): {},
            ('other', 'другое'): {},
        },
        ('garden structures, fencing', 'садовые конструкции'): {
            ('arches', 'арки'): {},
            ('fencing', 'ограждение'): {},
            ('gates', 'ворота'): {},
            ('greenhouses', 'теплицы'): {},
            ('letterboxes', 'почтовые ящики'): {},
            ('sheds, garages', 'сараи, гаражи'): {},
            ('other', 'другое'): {},
        },
        ('gardening supplies', 'расходные'): {
            ('fertilizer, soil amendments', 'удобрения, добавки'): {},
            ('tools, equipment', 'инструмент, оборудование'): {
                ('protective gear', 'защита'): {},
                ('pruners', 'секаторы'): {},
                ('moisture, pH meters', 'измерители влаги, pH'): {},
                ('rakes, shovels, hoes', 'грабли, лопаты, мотыги'): {},
                ('seeders, spreaders', 'сидеры, спредеры'): {},
                ('sprayers', 'опрыскиватели'): {},
                ('wheelbarrows', 'тачки'): {},
                ('kits', 'наборы'): {},
                ('other', 'другое'): {},
            },
            ('hydroponics, seed starting', 'гидропоника, высадка семян'): {
                ('grow lights', 'освещение'): {},
                ('hydroponics', 'гидропоника'): {},
                ('trays, shelves', 'лотки, полки'): {},
                ('other', 'другое'): {},
            },
            ('pest, weed control', 'контроль сорняков, вредителей'): {
                ('rodent', 'грызуны'): {},
                ('insect', 'насекомые'): {},
                ('mosquito', 'комары'): {},
                ('weed', 'сорняки'): {},
                ('other', 'другое'): {},
            },
            ('planters, pots', 'лотки, горшки'): {
                ('planters', 'лотки для высадки'): {},
                ('pots', 'горшки'): {},
                ('window boxes', 'оконные ящики'): {},
                ('other', 'другое'): {},
            },
            ('watering', 'полив'): {
                ('hoses, hose reels', 'шланги'): {},
                ('sprayers, nozzles', 'насадки'): {},
                ('sprinklers', 'разбрызгиватель'): {},
                ('valves', 'краны'): {},
                ('watering cans', 'лейки'): {},
                ('wather tanks', 'емкости'): {},
                ('other', 'другое'): {},
            },
        },
        ('lawnmowers', 'газонокосилки'): {
            ('riding mowers', 'райдеры'): {},
            ('walk-behind mowers', 'колесные'): {},
            ('parts, accessories', 'запчасти, аксессуары'): {},
            ('other', 'другое'): {},
        },
        ('outdoor cooking, eating', 'пикник, готовка'): {
            ('BBQ Tools', 'барбекью инструмент'): {},
            ('charcoal grills', 'угольные грилли'): {},
            ('coolers, ice', 'кулеры, лед'): {},
            ('gas grills', 'газовые грилли'): {},
            ('grill accessories', 'гриль аксессуары'): {},
            ('picnicware', 'посуда'): {},
            ('picnic baskets', 'корзины, сумки'): {},
            ('kits', 'наборы'): {},
            ('other', 'другое'): {},
        },
        ('outdoor furniture', 'мебель для улици'): {
            ('awnings, tents', 'тенты'): {},
            ('benches', 'скамейки'): {},
            ('chairs, loungers', 'кресла, жезлонги'): {},
            ('cushions, pads', 'подушки'): {},
            ('hammocks', 'гамаки'): {},
            ('marquees, gazebos', 'шатры, бельведеры'): {},
            ('tables', 'столы'): {},
            ('table and chair sets', 'столы, стулья'): {},
            ('swings', 'качели'): {},
            ('umbrellas', 'зонты'): {},
            ('patio sets', 'комплекты для патио'): {},
            ('other', 'другое'): {},
        },
        ('oudoor lighting', 'наружное освещение'): {
            ('lamp posts', 'столбы'): {},
            ('lanterns, strings', 'фонари, гирлянды'): {},
            ('light fixtures', 'крепеж освещения'): {},
            ('path lighting', 'освещение дорожек'): {},
            ('spotlights', 'мини прожектора'): {},
            ('floodlights', 'прожектора'): {},
            ('other', 'другое'): {},
        },
        ('pools, spas, saunas', 'бассейны, спа, сауны'): {
            ('pools, accessories', 'бассейны, аксессуары'): {
                ('accessories', 'аксессуары'): {},
                ('parts, maintenance', 'запчасти, обслуживание'): {},
                #pool chemicals
                #testing
                #Cleaners
                #Filters
                #Heaters
                #Liners
                #Pumps
                ('pools', 'бассейны'): {},
                ('pool covers', 'накрытия бассейнов'): {},
                ('other', 'другое'): {},
            },
            ('spas, hot tubs', 'спа'): {
                ('accessories', 'аксессуары'): {},
                ('parts, maintenance', 'запчасти, обслуживание'): {},
                ('spa covers', 'накрытия'): {},
                ('other', 'другое'): {},
            },
            ('saunas', 'сауны'): {
                ('heater stoves', 'печи'): {},
                ('accessories', 'аксессуары'): {},
                ('other', 'другое'): {},
            },
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('rugs, carpets', 'ковры, коврики'): {
        ('contemporary', 'современный дизайн'): {},
        ('different shapes', 'разные формы'): {},
        ('mats', 'маты'): {},
        ('outdoor', 'уличные'): {},
        ('runners', 'дорожки'): {},
        ('traditional', 'традиционные'): {},
        ('other', 'другое'): {},
    },
    ('window treatment', 'оконный декор'): {
        ('curtains', 'шторы, занавески'): {},
        ('curtain fabric', 'шторная ткань'): {},
        ('net curtains', 'тюль'): {},
        ('rods, tracks', 'карнизы'): {},
        ('roller blinds', 'роликовые шторы'): {},
        ('roman blinds', 'римские шторы'): {},
        ('thermal curtains', 'термические шторы'): {},
        ('venetian blinds', 'жалюзи'): {},
        ('rings, clips, hooks', 'кольца, крючки'): {},
        ('sets', 'наборы'): {},
        ('other', 'другое'): {},
    },
    ('other', 'другое'): {},
}}
