# -*- coding: utf-8 -*-
"""'pets' part of product categories dictionary.

Must hold subcategories of 'pets'
category in the form of python dictionary data type.

"""
pets = {('pets', 'домашние животные'): {
    ('birds', 'птицы'): {
        ('pet birds', 'домашнии птицы'): {},
        ('cages', 'клетки'): {},
        ('cage stands', 'подставки для клеток'): {},
        ('feeders', 'кормушки'): {},
        ('food, treats', 'питание, лакомства'): {},
        ('health care', 'здоровье, забота'): {},
        ('incubators', 'инкубаторы'): {},
        ('perches', 'насесты'): {},
        ('toys', 'игрушки'): {},
        ('other', 'другое'): {},
    },
    ('cats', 'кошки'): {
        ('apparel', 'одежда'): {},
        ('beds', 'постели'): {},
        ('behavior training', 'воспитание'): {},
        ('pet cats', 'домашнии кошки'): {},
        ('cages, carriers', 'клетки, переноски'): {},
        ('claw control', 'контроль когтей'): {},
        ('collars, tags', 'ошейники, теги'): {},
        ('dishes, feeders', 'посуда, кормушки'): {},
        ('cage stands', 'подставки для клеток'): {},
        ('doors, flaps', 'дверки'): {},
        ('flea, tick control', 'контроль блох, клещей'): {},
        ('food, treats', 'питание, лакомства'): {},
        ('furniture, scratchers', 'мебель, когтеточки'): {},
        ('litter', 'наполнитель туалетов'): {},
        ('litter boxes', 'лотки, туалеты'): {},
        ('health care', 'здоровье, забота'): {},
        ('pheromone', 'феромоны'): {},
        ('toys', 'игрушки'): {},
        ('other', 'другое'): {},
    },
    ('dogs', 'собаки'): {
        ('apparel', 'одежда'): {
            ('bandanas, scarves', 'банданы, шарфы'): {},
            ('bows', 'галстук, бабочка'): {},
            ('coats', 'пальто'): {},
            ('costumes', 'маскарад, образы'): {},
            ('diapers', 'подгузники'): {},
            ('dresses', 'платья'): {},
            ('hats, visors', 'головные уборы'): {},
            ('pajamas', 'пижамы'): {},
            ('trousers, shorts', 'брюки, шорты'): {},
            ('rain coats', 'плащи'): {},
            ('safety vests', 'жилеты безопасности'): {},
            ('shirts', 'рубашки'): {},
            ('shoes', 'обувь'): {},
            ('sport jerseys', 'толстовки'): {},
            ('sunglasses', 'очки темные'): {},
            ('sweaters', 'свитеры'): {},
            ('vests', 'жилеты'): {},
            ('other', 'другое'): {},
        },
        ('beds', 'постели'): {},
        ('blankets', 'одеяла'): {},
        ('carriers', 'переноски'): {},
        ('car seat covers', 'подстилки в машину'): {},
        ('collars, tags', 'ошейники, теги'): {},
        ('crates', 'клетки'): {},
        ('dishes, feeders', 'посуда, кормушки'): {},
        ('doghouses', 'конура'): {},
        ('fences, exercise pens', 'огорождения, площадки'): {},
        ('flea, tick control', 'контроль блох, клещей'): {},
        ('food, treats', 'питание, лакомства'): {},
        ('grooming', 'уход'): {
            ('clippers', 'клиперы'): {},
            ('deshedding tools', 'фурминатор'): {},
            ('dryers', 'фены'): {},
            ('grooming tables', 'столы'): {},
            ('brushes, combs', 'расчески, щетки'): {},
            ('washing', 'мытье'): {},
            ('other', 'другое'): {},
        },
        ('harnesses', 'упряжки, шлейки'): {},
        ('health care', 'здоровье, забота'): {
            ('ear care', 'уши'): {},
            ('eye care', 'глаза'): {},
            ('oral hygiene', 'полость рта'): {},
            ('skin, coat care', 'кожа, шерсть'): {},
            ('vitamins, supplements', 'витамины, добавки'): {},
            ('wormer products', 'противоглистные'): {},
            ('other', 'другое'): {},
        },
        ('leads, leashes', 'поводки'): {},
        ('muzzles', 'намордники'): {},
        ('pet memorials', 'памятники, мемориалы'): {},
        ('waste disposal, bags', 'утилизация отходов'): {},
        ('plaques, signs', 'таблички, знаки'): {},
        ('strollers', 'коляски'): {},
        ('toys', 'игрушки'): {},
        ('training, obedience', 'тренинг'): {
            ('agility training', 'подвижность'): {},
            ('spray collars', 'ошейник спрей'): {},
            ('house training pads', 'тренинговые площадки'): {},
            ('shock collars', 'ошейник шок'): {},
            ('sonic trainers', 'звуковые устройства'): {},
            ('training leads, leashes', 'поводки для тренинга'): {},
            ('videos, books', 'видео, книги'): {},
            ('whistles', 'свистки'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('fish', 'рыбки'): {
        ('aquariums, fish tanks', 'аквариумы'): {},
        ('aquatic plants', 'водоросли'): {},
        ('cleaning', 'очистка'): {},
        ('water treatments', 'обработка воды'): {},
        ('coral', 'кораллы'): {},
        ('crabs', 'крабы'): {},
        ('decorations', 'декор'): {},
        ('fish', 'рыбки для аквариума'): {},
        ('fish bowls', 'аквариумы круглые'): {},
        ('fish food', 'корм'): {},
        ('health care', 'здоровье, забота'): {},
        ('heating', 'обогрев'): {},
        ('lighting', 'освещение'): {},
        ('meters, regulators', 'измерители, регуляторы'): {},
        ('pumps, filters', 'насосы, фильтры'): {},
        ('snails', 'улитки'): {},
        ('stands', 'подставки'): {},
        ('stones, pebbles', 'камни, гравий'): {},
        ('other', 'другое'): {},
    },
    ('lost, found', 'пропал, найден'): {
        ('lost', 'пропал'): {
            ('cats', 'кошки'): {},
            ('dogs', 'собаки'): {},
            ('other', 'другое'): {},
        },
        ('found', 'найден'): {
            ('cats', 'кошки'): {},
            ('dogs', 'собаки'): {},
            ('other', 'другое'): {},
        },
    },
    ('small animals', 'маленькие животные'): {
        ('accessories', 'аксессуары'): {},
        ('cages', 'клетки'): {},
        ('health care', 'здоровье, забота'): {},
        ('pets', 'домашние животные'): {},
        ('other', 'другое'): {},
    },
    ('reptiles', 'рептилии'): {
        ('accessories', 'аксессуары'): {},
        ('pets', 'домашние животные'): {},
        ('aquariums, terrariums', 'аквариумы, террариумы'): {},
        ('health care', 'здоровье, забота'): {},
        ('other', 'другое'): {},
    },
    ('other', 'другое'): {},
}
}
