# -*- coding: utf-8 -*-
"""'toys, models' part of product categories dictionary.

Must hold subcategories of 'toys, models'
category in the form of python dictionary data type.

"""
toys_models = {('toys, models', 'игрушки, модели'): {
    ('dolls, accessories', 'куклы, аксессуары'): {
        ('accessories', 'аксессуары'): {},
        ('clothing', 'одежда'): {},
        ('houses, furniture', 'дома, мебель'): {},
        ('dolls', 'куклы'): {},
        ('prams, strollers', 'коляски'): {},
        ('reborn', 'реборн'): {
            ('accessories', 'аксессуары'): {},
            ('dolls', 'куклы'): {},
            ('kits, parts', 'наборы, части'): {},
            ('other', 'другое'): {},
        },
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('action figures', 'фигурки, персонажи'): {
        ('anime', 'аниме'): {},
        ('animation', 'анимация'): {},
        ('comic books', 'комиксы'): {},
        ('military', 'военные'): {},
        ('sports', 'спорт'): {},
        ('transformers', 'трансформеры'): {},
        ('robots', 'роботы'): {},
        ('movies', 'фильмы'): {},
        ('video games', 'видео игры'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('soft toys', 'мягкая игрушка'): {
        ('bears', 'мишки'): {},
        ('character toys', 'персонажи'): {},
        ('stuffed animals', 'животные'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('building toys', 'строительные игры'): {
        ('lego', 'лего'): {},
        ('magnetic sets', 'магнитные'): {},
        ('other', 'другое'): {},
    },
    ('diecast', 'дайкаст'): {
        ('accessories', 'аксессуары'): {},
        ('aircraft', 'самолеты'): {},
        ('boats, ships', 'корабли, лодки'): {},
        ('racing cars', 'гоночные машины'): {},
        ('cars', 'машины'): {},
        ('trucks', 'грузовики'): {},
        ('vans', 'фургоны, микроавтобусы'): {},
        ('construction vehicles', 'строительная техника'): {},
        ('farm vehicles', 'сельхоз техника'): {},
        ('motorcycles', 'мотоциклы'): {},
        ('tanks, military vehicles', 'танки, военная техника'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('educational', 'учебные'): {
        ('art, craft', 'живопись, рукоделие'): {
            ('art sets', 'наборы для рисования'): {},
            ('stationery sets', 'канцтовары'): {},
            ('easels, blackboards', 'мольберты, доски'): {},
            ('paints, chalk', 'краски, мел'): {},
            ('pencils', 'карандаши'): {},
            ('playdough', 'пластилин'): {},
            ('stickers', 'стикеры'): {},
            ('bulk lots', 'оптом'): {},
            ('other', 'другое'): {},
        },
        ('alphabet, language', 'алфавит, язык'): {},
        ('geography, history', 'география, история'): {},
        ('learning systems', 'системы обучения'): {},
        ('computer games', 'компьютерные игры'): {},
        ('mathematics', 'математика'): {},
        ('music', 'музыка'): {},
        ('reading, writing', 'чтение, письмо'): {},
        ('science', 'наука'): {},
        ('special needs', 'особые потребности'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('electronic', 'электронные'): {},
    ('games', 'игры'): {
        ('chess, checkers', 'шахматы, шашки'): {},
        ('board games', 'настольные игры'): {},
        ('electronic games', 'электронные игры'): {},
        ('other', 'другое'): {},
    },
    ('models', 'модели'): {
        ('aircraft', 'самолеты'): {},
        ('cars', 'машины'): {},
        ('trucks', 'грузовики'): {},
        ('tanks, military vehicles', 'танки, военная техника'): {},
        ('railway', 'железная дорога'): {},
        ('boats, ships', 'корабли, лодки'): {},
        ('tools, supplies', 'инструмент, расходные'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('outdoor toys, structures', 'уличные игрушки, конструкции'): {
        ('inflatable bouncers', 'надувные замки'): {},
        ('climbing frames', 'конструкции для лазания'): {},
        ('paddling pools', 'маленькие бассейны'): {},
        ('sand pits', 'песочницы'): {},
        ('playhouses', 'домики'): {},
        ('sand, water toys', 'игрушки для песка, воды'): {},
        ('swings, slides', 'качели, горки'): {},
        ('tents, tunnels', 'тенты, туннели'): {},
        ('balls, ball games', 'мячи'): {},
        ('kites', 'воздушные змеи'): {},
        ('ride-ons', 'райд-он, каталки'): {
            ('battery powered', 'на батареях'): {},
            ('bikes, trikes', 'велосипеды'): {},
            ('cars', 'машины'): {},
            ('carts, trolleys', 'тележки, повозки'): {},
            ('bouncers', 'баунсеры'): {},
            ('rockers', 'качалки'): {},
            ('scooters', 'самокаты, скутеры'): {},
            ('other', 'другое'): {},
        },
        ('trampolines', 'батуты'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('pretend play', 'имитация, подражание'): {
        ('dress ups', 'наряды'): {
            ('animals', 'животные'): {},
            ('fairies, princesses', 'феи, принцессы'): {},
            ('super heroes', 'супер герои'): {},
            ('other', 'другое'): {},
        },
        ('dishes, tea sets', 'посуда, чайные наборы'): {},
        ('kitchen, housework', 'кухня, работа по дому'): {},
        ('tools, building', 'инструмент'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('radio control', 'радиоуправляемые'): {
        ('boats', 'лодки'): {},
        ('cars', 'машины'): {},
        ('helicopters', 'вертолеты'): {},
        ('parts, accessories', 'запчасти, аксессуары'): {
            ('boats', 'лодки'): {},
            ('cars', 'машины'): {},
            ('helicopters', 'вертолеты'): {},
            ('planes', 'самолеты'): {},
            ('robots', 'роботы'): {},
            ('trucks', 'грузовики'): {},
            ('tanks', 'танки'): {},
            ('other', 'другое'): {},
        },
        ('planes', 'самолеты'): {},
        ('robots', 'роботы'): {},
        ('trucks', 'грузовики'): {},
        ('tanks', 'танки'): {},
        ('other', 'другое'): {},
    },
    ('slot cars', 'авто треки'): {
        ('cars', 'машины'): {},
        ('sets', 'наборы'): {},
        ('tracks', 'треки'): {},
        ('bulk lots', 'оптом'): {},
        ('other', 'другое'): {},
    },
    ('jigsaws, puzzles', 'пазлы, головоломки'): {},
    ('furniture', 'мебель'): {
        ('armchairs, couches', 'кресла, диваны'): {},
        ('tables, chairs', 'столы, стулья'): {},
        ('other', 'другое'): {},
    },
    ('bulk lots', 'оптом'): {},
    ('other', 'другое'): {},
}
}
