# -*- coding: utf-8 -*-
"""'video games' part of product categories dictionary.

Must hold subcategories of 'video games'
category in the form of python dictionary data type.

"""
video_games = {('video games', 'видео игры'): {
    ('nintendo', 'nintendo'): {
        ('nintendo DS', 'nintendo DS'): {
            ('accessories', 'аксессуары'): {
                ('cases', 'чехлы, кейсы'): {},
                ('skins', 'скины'): {},
                ('chargers', 'зарядные устройства'): {},
                ('memory, storage', 'память'): {},
                ('screen protectors', 'защита экрана'): {},
                ('styluses', 'стилус'): {},
                ('other', 'другое'): {},
            },
            ('consoles', 'консоли'): {},
            ('games', 'игры'): {},
            ('other', 'другое'): {},
        },
        ('nintendo Wii', 'nintendo Wii'): {
            ('accessories', 'аксессуары'): {
                ('cables, leads', 'кабели'): {},
                ('controllers', 'контроллеры'): {},
                ('other', 'другое'): {},
            },
            ('consoles', 'консоли'): {},
            ('games', 'игры'): {},
            ('other', 'другое'): {},
        },
        ('other Nintendo', 'другие Nintendo'): {},
    },
    ('xbox', 'xbox'): {
        ('xbox', 'xbox'): {
            ('accessories', 'аксессуары'): {
                ('cables, leads', 'кабели'): {},
                ('controllers', 'контроллеры'): {},
                ('other', 'другое'): {},
            },
            ('consoles', 'консоли'): {},
            ('games', 'игры'): {
                ('action, adventure', 'приключения'): {},
                ('fighting', 'бои, сражения'): {},
                ('kids, educational', 'учебные, детские'): {},
                ('music', 'музыка'): {},
                ('puzzle', 'пазлы'): {},
                ('racing', 'гонки'): {},
                ('role playing', 'ролевые игры'): {},
                ('shooter', 'стрелялки'): {},
                ('simulation', 'симуляторы'): {},
                ('sports', 'спорт'): {},
                ('strategy', 'стратегии'): {},
                ('other', 'другое'): {},
            },
        },
        ('xbox 360', 'xbox 360'): {
            ('accessories', 'аксессуары'): {
                ('cables, leads', 'кабели'): {},
                ('controllers', 'контроллеры'): {},
                ('headsets', 'наушники'): {},
                ('memory', 'память'): {},
                ('other', 'другое'): {},
            },
            ('consoles', 'консоли'): {},
            ('games', 'игры'): {
                ('action, adventure', 'приключения'): {},
                ('fighting', 'бои, сражения'): {},
                ('kids, educational', 'учебные, детские'): {},
                ('music', 'музыка'): {},
                ('puzzle', 'пазлы'): {},
                ('racing', 'гонки'): {},
                ('role playing', 'ролевые игры'): {},
                ('shooter', 'стрелялки'): {},
                ('simulation', 'симуляторы'): {},
                ('sports', 'спорт'): {},
                ('strategy', 'стратегии'): {},
                ('other', 'другое'): {},
            },
        },
    },
    ('PlayStation', 'PlayStation'): {
        ('PlayStation', 'PlayStation'): {
            ('accessories', 'аксессуары'): {
                ('cables, leads', 'кабели'): {},
                ('controllers', 'контроллеры'): {},
                ('memory', 'память'): {},
                ('other', 'другое'): {},
            },
            ('consoles', 'консоли'): {},
            ('games', 'игры'): {
                ('action, adventure', 'приключения'): {},
                ('fighting', 'бои, сражения'): {},
                ('kids, educational', 'учебные, детские'): {},
                ('music', 'музыка'): {},
                ('puzzle', 'пазлы'): {},
                ('racing', 'гонки'): {},
                ('role playing', 'ролевые игры'): {},
                ('shooter', 'стрелялки'): {},
                ('simulation', 'симуляторы'): {},
                ('sports', 'спорт'): {},
                ('strategy', 'стратегии'): {},
                ('other', 'другое'): {},
            },
        },
        ('PlayStation 2', 'Playstation 2'): {
            ('accessories', 'аксессуары'): {
                ('cables, leads', 'кабели'): {},
                ('controllers', 'контроллеры'): {},
                ('memory', 'память'): {},
                ('other', 'другое'): {},
            },
            ('consoles', 'консоли'): {},
            ('games', 'игры'): {
                ('action, adventure', 'приключения'): {},
                ('fighting', 'бои, сражения'): {},
                ('kids, educational', 'учебные, детские'): {},
                ('music', 'музыка'): {},
                ('puzzle', 'пазлы'): {},
                ('racing', 'гонки'): {},
                ('role playing', 'ролевые игры'): {},
                ('shooter', 'стрелялки'): {},
                ('simulation', 'симуляторы'): {},
                ('sports', 'спорт'): {},
                ('strategy', 'стратегии'): {},
                ('other', 'другое'): {},
            },
        },
        ('PlayStation 3', 'Playstation 3'): {
            ('accessories', 'аксессуары'): {
                ('cables, leads', 'кабели'): {},
                ('controllers', 'контроллеры'): {},
                ('skins', 'скины'): {},
                ('other', 'другое'): {},
            },
            ('consoles', 'консоли'): {},
            ('games', 'игры'): {
                ('action, adventure', 'приключения'): {},
                ('fighting', 'бои, сражения'): {},
                ('kids, educational', 'учебные, детские'): {},
                ('music', 'музыка'): {},
                ('puzzle', 'пазлы'): {},
                ('racing', 'гонки'): {},
                ('role playing', 'ролевые игры'): {},
                ('shooter', 'стрелялки'): {},
                ('simulation', 'симуляторы'): {},
                ('sports', 'спорт'): {},
                ('strategy', 'стратегии'): {},
                ('other', 'другое'): {},
            },
        },
        ('PSP', 'PSP'): {
            ('accessories', 'аксессуары'): {
                ('batteries, chargers', 'батареи, зарядки'): {},
                ('cases', 'чехлы, кейсы'): {},
                ('screen protectors', 'защита экрана'): {},
                ('speakers, remotes', 'колонки, пульты'): {},
                ('cables, leads', 'кабели'): {},
                ('skins', 'скины'): {},
                ('other', 'другое'): {},
            },
            ('consoles', 'консоли'): {},
            ('games', 'игры'): {
                ('action, adventure', 'приключения'): {},
                ('fighting', 'бои, сражения'): {},
                ('kids, educational', 'учебные, детские'): {},
                ('music', 'музыка'): {},
                ('puzzle', 'пазлы'): {},
                ('racing', 'гонки'): {},
                ('role playing', 'ролевые игры'): {},
                ('shooter', 'стрелялки'): {},
                ('simulation', 'симуляторы'): {},
                ('sports', 'спорт'): {},
                ('strategy', 'стратегии'): {},
                ('other', 'другое'): {},
            },
            ('movies', 'фильмы'): {
                ('action, adventure', 'приключения'): {},
                ('animation', 'анимация'): {},
                ('anime, manga', 'аниме, манга'): {},
                ('kids', 'детское'): {},
                ('classics', 'классика'): {},
                ('comedy', 'комедия'): {},
                ('concert, music', 'концерты, музыка'): {},
                ('documentary', 'документальные'): {},
                ('drama', 'драма'): {},
                ('educational', 'учебные'): {},
                ('exercise, fitness', 'фитнес'): {},
                ('family', 'семейные'): {},
                ('foreign language', 'иностранный язык'): {},
                ('horror', 'ужасы'): {},
                ('independent, art house', 'независимое производство'): {},
                ('musicals, broadway', 'мюзикл'): {},
                ('mystery, suspense', 'мистерия'): {},
                ('religious', 'религиозный мотив'): {},
                ('romance', 'романтичное'): {},
                ('sci-fi, fantasy', 'sci-fi, фэнтези'): {},
                ('sports', 'спорт'): {},
                ('television shows', 'телевизионные шоу'): {},
                ('thriller', 'триллер'): {},
                ('western', 'вестерн'): {},
                ('other', 'другое'): {},
            },
        },
    },
    ('PC gaming', 'персональный компьютер'): {
        ('accessories', 'аксессуары'): {},
        ('PC games', 'компьютерные игры'): {
            ('action, adventure', 'приключения'): {},
            ('fighting', 'бои, сражения'): {},
            ('kids, educational', 'учебные, детские'): {},
            ('music', 'музыка'): {},
            ('puzzle', 'пазлы'): {},
            ('racing', 'гонки'): {},
            ('role playing', 'ролевые игры'): {},
            ('shooter', 'стрелялки'): {},
            ('simulation', 'симуляторы'): {},
            ('sports', 'спорт'): {},
            ('strategy', 'стратегии'): {},
            ('other', 'другое'): {},
        },
        ('other', 'другое'): {},
    },
    ('other', 'другое'): {},
}
}
